--CTAS_NVAS_JUSTME
CREATE OR REPLACE TABLE `crp-pro-cx-analitica.mus_pro_negfin_tablas_finales.DIM_NEGFIN_TM_CTAS_NVS_JUSTME` AS 
with CTA AS (
  SELECT
    A.CTA_CVE, 
    A.TIP_INF,
    A.LOG_CVE,
    TDA_ADM_CTA,
    A.CTA_FCH_ALTA,
    EXTRACT(YEAR FROM A.CTA_FCH_ALTA) AS ANIO_ALTA,
    EXTRACT(MONTH FROM A.CTA_FCH_ALTA) AS MES_ALTA, 
    B.SEX_CVE AS SEXO,
    B.CTE_FCH_NAC
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` AS A 
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES_VPL` AS B ON A.CTA_CVE = B.CTA_CVE AND A.LOG_CVE = B.LOGO AND A.CTA_FCH_ALTA = B.CTE_FCH_ALT
  WHERE A.LOG_CVE = 120 AND A.TIP_INF = 100 AND A.CTA_FCH_ALTA >= '2025-12-01'
)
SELECT 
  CTA_CVE,
  TIP_INF,
  LOG_CVE,
  CTA_FCH_ALTA,
  TDA_ADM_CTA,
  ANIO_ALTA,
  MES_ALTA,
  SEXO,
  CTE_FCH_NAC,
  ANIO_ALTA*100+MES_ALTA AS ANIOMES_ALTA,
  CURRENT_DATE('America/Mexico_City') AS FCH_CARGA
FROM CTA 
