CREATE OR REPLACE TABLE  crp-pro-dwh-semanticagold.MUS_PRO_DWH_SAS_TEMP.TMP_FAC_DISPOSICIONES_JUN_3 AS (
WITH TIEMPO AS ( SELECT 2025 AS ANIO, DATE('2017-01-01') AS FCH_INI, DATE('2026-12-31') AS FCH_FIN ),

TITULAR AS ( SELECT * FROM  (
                                        SELECT CTA_CVE,
                                            SUM(CANT_ADIC) AS FLG_ADIC,
                                            SUM(CANT_TIT) AS FLG_TITU
                                        FROM (

                                                SELECT A.CTA_CVE
                                                ,0 AS CANT_TIT
                                                ,COUNT((A.TRJ_NUM)) AS CANT_ADIC
                                                FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` AS A
                                                WHERE IND_TIT IN ('1',' ') 
                                                AND A.TRJ_EDO_CVE NOT IN ('A ','B ','C ','E ','F','H ','J ','K ','O ','P ','Q ','S ','U ','X ','Y ','Z')
                                                GROUP BY 1

                                UNION ALL

                                SELECT B.CTA_CVE
                                ,COUNT((B.TRJ_NUM)) AS CANT_TIT
                                ,0 AS CANT_ADIC
                                FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` AS B
                                WHERE IND_TIT='0'AND 
                                B.TRJ_EDO_CVE NOT IN ('A ','B ','C ','E ','F','H ','J ','K ','O ','P ','Q ','S ','U ','X ','Y ', 'Z')
                                                    GROUP BY 1
                                            ) 
                                        GROUP BY 1
                                ) ),

CTE_UNICO AS ( SELECT CTA_CVE, CTE_CVE_UNICO FROM (SELECT  CTA_CVE, CTE_CVE_UNICO,Row_number() over (partition by B.CTA_CVE ORDER BY B.CTA_CVE) AS REGISTRO
                                                        FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` as B
                                                ) WHERE REGISTRO=1),
                          DIMENSIONAL AS(   SELECT   A.CTA_CVE, A.TIP_INF,ANIO_ESTR, MES_ESTR,CTA_FCH_ALTA,PLAN_CVE, CASE WHEN PLAN_CVE IN (20002) THEN 'ATM' WHEN PLAN_CVE IN (20003) THEN 'POS' WHEN PLAN_CVE IN (20004) THEN 'DIGITAL'  ELSE 'POS' END AS FLG_CANAL, --CAMPO AGREGADO
                               --CASE WHEN CTA_NIV_MOR IN (3,4,5,6,7,8,9)  THEN 1 ELSE 0 END AS FLG_30,
                    --CASE WHEN CTA_NIV_MOR IN (5,6,7,8,9) THEN 1 ELSE 0 END AS FLG_90,
                                
                                       
                                        CANT_TRN,
                                         IMP_TRN
                                FROM (
                                          SELECT  CTA_CVE, A.TIP_INF, ANIO AS ANIO_ESTR,
                                                    MES AS MES_ESTR,  A.TRN_CVE,PLAN_CVE ,ROW_NUMBER() OVER(PARTITION BY CTA_CVE) AS ID,
                                                    -- CTA_NIV_MOR,
                                                    
                                                   CASE WHEN (A.TRN_CVE IN (2,102,320,122) AND A.TIP_INF =110) THEN  1
                                                        WHEN (A.TRN_CVE IN (2,102,320,1002,1102,2002,2102,122) AND A.TIP_INF =100) THEN 1
                                                         WHEN (/*TRN_CVE  IN (789,339)*/  PLAN_CVE IN (20003,20004) and a.TRN_CVE  in (12,122) AND A.TIP_INF IN (200, 210) ) THEN 1
                                                    ELSE 0 END AS CTOS_IMP, 
                                                    TRN_IMP AS IMP_TRN, TRN AS CANT_TRN
                                                    
                                                
                                            FROM (
                                                        with Base_ini as
(
SELECT FCH_FCH,CASE WHEN PLAN_CVE IN (20002) THEN 'ATM' WHEN PLAN_CVE IN (20003) THEN 'POS' WHEN PLAN_CVE IN (20004) THEN 'DIGITAL'  ELSE 'POS' END AS FLG_CANAL, EXTRACT(YEAR FROM FCH_FCH )AS ANIO, EXTRACT(MONTH FROM FCH_FCH )AS MES,  A.CTA_CVE, SUM( CASE WHEN A.TRN_CVE in (62, 262, 420,1062,1262 ) THEN TRN_IMP*-1             
                                                WHEN (A.TRN_CVE in (2,12,102,122,320,1002,1102,2002,2102) ) THEN TRN_IMP         
                                                ELSE 0 END) AS IMP_TRN,
                                                 SUM( CASE WHEN A.TRN_CVE in (62, 262, 420,1062,1262 ) THEN -1             
                                                WHEN (A.TRN_CVE in (2,12,102,122,320,1002,1102,2002,2102) ) THEN 1         
                                                ELSE 0 END) AS TRN,
                                                
                                                 LOG_CVE, TIP_INF, TRN_CVE, a.TDA_CVE, PLAN_CVE,TRN_IMP,  
                                                 CASE WHEN B.CTA_ACT IS NOT NULL THEN B.CTA_ACT ELSE A.CTA_CVE END AS CTA_TRACK
FROM crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD AS A 
LEFT JOIN crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK  B ON A.CTA_CVE=B.CTA_CVE
where FCH_FCH  between (SELECT FCH_INI FROM TIEMPO )   and (SELECT FCH_FIN FROM TIEMPO ) and PLAN_CVE in (20002,20003, 20004) and TRN_CVE in (62, 262, 420,1062,1262,2,12,102,122,320,1002,1102,2002,2102) AND TIP_INF IN (110,100,210,200)
 --and TRN_IMP > 11000
group by all
), 

BASE_MEDIA as
(
SELECT PLAN_CVE, ANIO, MES, TIP_INF, CTA_TRACK,TDA_CVE, SUM(TRN) AS TRN, SUM (IMP_TRN) AS MONTO,  
FROM Base_ini
GROUP BY ALL
), -- select * from base_media,



BASE_CTA AS
(SELECT ANIO,MES,TIP_INF, CTA_TRACK,TDA_CVE, COUNT(CTA_TRACK)AS TOTAL
FROM BASE_MEDIA
WHERE MONTO > 0
GROUP BY ALL)

SELECT A.CTA_TRACK AS CTA_CVE,A.TIP_INF,B.PLAN_CVE,TRN_CVE,A.ANIO,A.MES,A.MONTO AS TRN_IMP,A.TRN FROM (SELECT A.ANIO,A.TIP_INF,A.MES,A.TDA_CVE,A.CTA_TRACK, COUNT(DISTINCT A.CTA_TRACK) AS CTAS, SUM(B.MONTO) AS MONTO,SUM(B.TRN) AS TRN
FROM BASE_CTA AS A
INNER JOIN BASE_MEDIA AS B
ON A.CTA_TRACK=B.CTA_TRACK AND A.ANIO=B.ANIO AND A.MES=B.MES
GROUP BY ALL) AS A 
LEFT JOIN ( SELECT *, ROW_NUMBER() OVER(PARTITION BY CTA_TRACK,ANIO_PLAN,MES_PLAN) AS ID FROM (SELECT CASE WHEN B.CTA_ACT IS NOT NULL THEN B.CTA_ACT ELSE A.CTA_CVE END AS CTA_TRACK,EXTRACT(YEAR FROM FCH_FCH) AS ANIO_PLAN,EXTRACT(MONTH FROM FCH_FCH) AS MES_PLAN,TIP_INF,PLAN_CVE,TRN_CVE,SUM( CASE WHEN A.TRN_CVE in (62, 262, 420,1062,1262 ) THEN -1             
                                                WHEN (A.TRN_CVE in (2,12,102,122,320,1002,1102,2002,2102) ) THEN 1         
                                                ELSE 0 END) AS TRN,
                                                
FROM crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD AS A 
LEFT JOIN crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK  B ON A.CTA_CVE=B.CTA_CVE
where FCH_FCH  between (SELECT FCH_INI FROM TIEMPO )   and (SELECT FCH_FIN FROM TIEMPO ) and PLAN_CVE in (20002,20003, 20004) and TRN_CVE in (62, 262, 420,1062,1262,2,12,102,122,320,1002,1102,2002,2102) AND TIP_INF IN (100,110,210,200) GROUP BY ALL)) AS B ON (A.CTA_TRACK = B.CTA_TRACK AND A.ANIO=B.ANIO_PLAN AND A.MES=B.MES_PLAN)
WHERE ID = 1 

                                                ) AS A	
                                           
                                           
                                    ) AS A
                LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` AS C ON A.CTA_CVE=C.CTA_CVE ),


              DISPOSICIONES AS   (select * from (SELECT A.CTA_CVE,A.ANIO_ESTR,A.MES_ESTR,A.TIP_INF,A.CANT_TRN,A.IMP_TRN,ANIO_OBS,
          MES_OBS,
         FLG_PAPER,
         NIV_RIESGO,
         RANG_NIV_MOR,
         RANG_TASA_RBP,
         RANG_UTILIZA,
         RANG_SDO_ACT,
         CTA_EDO_CVE,
          ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) AS MOBS_ALT,
          (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA))) AS MOBS_ALT_ESTR, 
        ((A.ANIO_ESTR*100)+A.MES_ESTR) AS ANIOMES_ESTR,((B.ANIO_OBS*100)+B.MES_OBS) AS ANIOMES_OBS, 
        CTA_TDA_APE, 
        CTA_SDO_ACT,
        B.LOG_CVE,
        CTA_TASA_RBP,
        CTA_NIV_MOR,
        CTA_SDO_TOTALERO,
        CTA_TOTALERO_FLG,
        A.CTA_FCH_ALTA,
        FLG_CANAL, 
        PLAN_CVE,
        B.CTA_IMP_LIM_CRD, 
        CASE WHEN CTA_NIV_MOR IN (3,4,5,6,7,8,9)  THEN 1 ELSE 0 END AS FLG_30,
         CASE WHEN CTA_NIV_MOR IN (5,6,7,8,9) THEN 1 ELSE 0 END AS FLG_90,
          CASE WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=12 THEN 'Y1' 
                                    WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=24 THEN 'Y2'
                                    WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=36 THEN 'Y3'
                                    WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=48 THEN 'Y4'
                            ELSE 'OTRO' END AS YTD_ESTR,
            CASE WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 4000 THEN '1.-4,000'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 7500 THEN '2.-4,000-7,499'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 10000 THEN '3.-7,500-9,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 15000 THEN '4.-10,000-14,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 20000 THEN '5.-15,000-19,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 30000 THEN '6.-20,000-29,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 50000 THEN '7.-30,000-49,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD >= 50000 THEN '50,000+'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 2000 THEN '1.-0-1,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 4000 THEN '2.-2,000-3,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 8000 THEN '3.-4,000-7,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 12000 THEN '4.-8,000-11,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 15000 THEN '5.-12,000 -14,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 18000 THEN '6.-15,000-17,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 20000 THEN '7.-18,000-19,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD >= 20000 THEN '>=20,000'
                            ELSE 'OTRO' END AS RANG_LIM_CRD, 
                            CASE WHEN ANIO_ESTR<2009 THEN 2009 ELSE ((ANIO_ESTR*100)+MES_ESTR) END AS COSECHA,
                             CASE WHEN B.CTA_SDO_ACT>0 THEN 1 ELSE 0 END AS CTA_CON_SDO,
                             CTA_MISC_CR_SCORE,
                           
                            CASE WHEN B.CTA_IMP_LIM_CRD<=0 THEN -1 ELSE B.CTA_SDO_ACT/B.CTA_IMP_LIM_CRD END AS PRCT_UTI,

        
        
        
         /*
         CASE WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) < 7 THEN '1.- 0-6 Meses'---((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) = MOBS_ALT
                          WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) < 13 THEN '2.- 7-12 Meses'
                          WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) < 25 THEN '3.- 13-24 Meses'
                          WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) < 73 THEN '4.- 25-72 Meses'
                          WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) < 121 THEN '5.- 73-120 Meses'
                          WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) >= 121 THEN '6.- 120+ Meses'
                          WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) is null THEN '0.- NO CLASIFICADO'
                        END AS RANG_MOBS,
        */
       
    
        CASE WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=6 THEN 'A.0M-6M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=12 THEN 'B.7M-12M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=24 THEN 'C.13M-24M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=36 THEN 'D.25M-36M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=48 THEN 'E.37M-48M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=60 THEN 'F.49M-60M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) >=61 THEN 'G.61M+'

        ELSE '0.- NO CLASIFICADO' END AS RANG_MOBS,


        
                        CASE WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE BETWEEN 406 AND 417 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=436 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=449 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=463 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE>=464 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<406 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE BETWEEN 406 AND 417 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=436 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=449 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE>=450 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<406 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE BETWEEN 400 AND 419 THEN 10
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=435 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=444 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE>=445 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<400 THEN 0

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE BETWEEN 382 AND 418 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=477 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=527 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=590 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE>=591 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<382 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE BETWEEN 382 AND 418 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=477 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=527 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE>=528 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<382 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE BETWEEN 368 AND 423 THEN 10
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=474 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=508 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE>=509 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<368 THEN 0

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE BETWEEN 840 AND 859 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=883 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=889 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE>=890 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<840 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE BETWEEN 840 AND 859 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=883 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=933 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE>=934 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<840 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=819 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=833 THEN 10
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=883 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=917 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE>=918 THEN 13 
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<800 THEN 0 

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 17
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 443 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=526 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=553 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE>=554 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<375 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 443 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=526 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=704 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE>=705 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<375 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 413 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=460 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=480 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=540 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=583 THEN 15
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE>=584 THEN 16 
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<375 THEN 10 

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 15

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=12 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=12 AND B.CTA_MISC_CR_SCORE>=526 THEN 2

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE<375 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE BETWEEN 526 AND 603 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE>=604 THEN 6

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE<375 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE BETWEEN 526 AND 603 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE>=604 THEN 10

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE<375 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE BETWEEN 526 AND 603 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE>=604 THEN 14

                        END AS CVE_NODO              
              FROM DIMENSIONAL AS A
              LEFT JOIN (SELECT DISTINCT 
                                 CASE WHEN B.CTA_ACT IS NOT NULL THEN B.CTA_ACT ELSE A.CTA_CVE END AS CTA_TRACK, 
                                TIP_INF,
                                ANIO AS ANIO_OBS,
                                MES AS MES_OBS,
                                LOG_CVE,
                                CTA_TDA_APE,  
                                CTA_IMP_LIM_CRD,
                                CTA_SDO_ACT,
                                A.CTA_EDO_CVE, 
                                CTA_NVO_FACTOR_TASA AS CTA_TASA_RBP,
                                CTA_NIV_MOR,
                                CTA_FCH_ULT_PAG,
                                CTA_IMP_ULT_PAGO,
                                CTA_SDO_TOTALERO,
                                CTA_TOTALERO_FLG,
                                CTA_FCH_PRM_CMP,
                                CTA_TASA_FLG AS CTA_TASA_RBP_FLG,
                                CTA_MISC_CR_SCORE,
                                CASE WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 4000 THEN '1.-4,000'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 7500 THEN '2.-4,000-7,499'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 10000 THEN '3.-7,500-9,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 15000 THEN '4.-10,000-14,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 20000 THEN '5.-15,000-19,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 30000 THEN '6.-20,000-29,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 50000 THEN '7.-30,000-49,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD >= 50000 THEN '8.-50,000+'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 2000 THEN '1.-0-1,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 4000 THEN '2.-2,000-3,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 8000 THEN '3.-4,000-7,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 12000 THEN '4.-8,000-11,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 15000 THEN '5.-12,000 -14,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 18000 THEN '6.-15,000-17,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 20000 THEN '7.-18,000-19,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD >= 20000 THEN '8.->=20,000'
                                                ELSE 'OTRO' END AS RANG_LIM_CRD,
                                                 CASE WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 4000 THEN '1.-4,000'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 7500 THEN '2.-4,000-7,499'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 10000 THEN '3.-7,500-9,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 15000 THEN '4.-10,000-14,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 20000 THEN '5.-15,000-19,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 30000 THEN '6.-20,000-29,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 50000 THEN '7.-30,000-49,999'
                                                    WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT >= 50000 THEN '8.-50,000+'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 2000 THEN '1.-0-1,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 4000 THEN '2.-2,000-3,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 8000 THEN '3.-4,000-7,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 12000 THEN '4.-8,000-11,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 15000 THEN '5.-12,000 -14,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 18000 THEN '6.-15,000-17,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 20000 THEN '7.-18,000-19,999'
                                                    WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT >= 20000 THEN '8.->=20,000'
                                            ELSE 'OTRO' END RANG_SDO_ACT,
                                              CASE WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.20 THEN 'A.1-20'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.25 THEN 'B.21-25'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.30 THEN 'C.26-30'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.35 THEN 'D.31-35'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.40 THEN 'E.36-40'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.45 THEN 'F.41-45'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.50 THEN 'G.46-50'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.75 THEN 'H.51-75'
                                                    WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.85 THEN 'I.76-85'
                                            ELSE 'J.86+' END AS RANG_UTILIZA,
                                             CASE WHEN CTA_NVO_FACTOR_TASA=14.99 AND A.TIP_INF NOT IN (200,210) THEN 'T0'
                                                WHEN CTA_NVO_FACTOR_TASA=26.55 AND A.TIP_INF NOT IN (200,210) THEN 'Empleado'
                                                WHEN CTA_NVO_FACTOR_TASA=31.39 AND A.TIP_INF NOT IN (200,210) THEN 'T1'
                                                WHEN CTA_NVO_FACTOR_TASA=42.04 AND A.TIP_INF NOT IN (200,210) THEN 'T2'
                                                WHEN CTA_NVO_FACTOR_TASA=53.11 AND A.TIP_INF NOT IN (200,210) THEN 'T3'
                                                WHEN CTA_NVO_FACTOR_TASA=61.2 AND A.TIP_INF NOT IN (200,210) THEN 'T4'
                                                WHEN CTA_NVO_FACTOR_TASA=66 AND A.TIP_INF NOT IN (200,210) THEN 'T5'
                                                WHEN CTA_NVO_FACTOR_TASA=38.71 AND A.TIP_INF NOT IN (100,110) THEN 'Empleado'
                                                WHEN CTA_NVO_FACTOR_TASA=77.42 AND A.TIP_INF NOT IN (100,110) THEN 'T3'
                                                WHEN CTA_NVO_FACTOR_TASA=80 AND A.TIP_INF NOT IN (100,110) THEN 'T4'
                                                WHEN CTA_NVO_FACTOR_TASA=85 AND A.TIP_INF NOT IN (100,110) THEN 'T5'
                                        ELSE 'OTRO' END AS RANG_TASA_RBP,
                                         CASE WHEN CTA_NIV_MOR IN (0,1) THEN '0.-CTAS_VIG'
                                                WHEN CTA_NIV_MOR=2 THEN '1.-1-29 DIAS'
                                                WHEN CTA_NIV_MOR=3 THEN '2.-30_DIAS'
                                                WHEN CTA_NIV_MOR=4 THEN '3.-60_DIAS'
                                                WHEN CTA_NIV_MOR=5 THEN '4.-90_DIAS'
                                                WHEN CTA_NIV_MOR=6 THEN '5.-120_DIAS'
                                                WHEN CTA_NIV_MOR=7 THEN '6.-150_DIAS'
                                                WHEN CTA_NIV_MOR=8 THEN '7.-180_DIAS'
                                        ELSE '8.-210_DIAS' END AS RANG_NIV_MOR,
                                        CASE WHEN TIP_INF=100 AND  date(ANIO,MES,1) <= '2022-01-01' THEN 
    
CASE WHEN (CTA_MISC_CR_SCORE) =0   THEN '0.No calificado'
     WHEN (CTA_MISC_CR_SCORE)<=405 THEN '1.VERY HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=426 THEN '2.HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=450 THEN '3.MEDIUM'
     WHEN (CTA_MISC_CR_SCORE)<=467 THEN '4.LOW'
     WHEN (CTA_MISC_CR_SCORE)>=468 THEN '5.VERY LOW'

     END

     WHEN TIP_INF=100 AND date(ANIO,MES,1) >= '2022-02-01' THEN 
CASE WHEN (CTA_MISC_CR_SCORE) =0   THEN '0.No calificado'
     WHEN (CTA_MISC_CR_SCORE)<=455 THEN '1.VERY HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=525 THEN '2.HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=603 THEN '3.MEDIUM'
     WHEN (CTA_MISC_CR_SCORE)<=661 THEN '4.LOW'
     WHEN (CTA_MISC_CR_SCORE)>661  THEN '5.VERY LOW'
   
     END
     WHEN TIP_INF=110 AND date(ANIO,MES,1) <= '2022-03-01' THEN 

CASE WHEN (CTA_MISC_CR_SCORE) =0   THEN '0.No calificado'
     WHEN (CTA_MISC_CR_SCORE)<=856 THEN '1.VERY HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=894 THEN '2.HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=929 THEN '3.MEDIUM'
     WHEN (CTA_MISC_CR_SCORE)<=952 THEN '4.LOW'
     WHEN (CTA_MISC_CR_SCORE)>=953 THEN '5.VERY LOW' 
     END

WHEN TIP_INF=110 AND date(ANIO,MES,1) >= '2022-04-01' THEN 

CASE WHEN (CTA_MISC_CR_SCORE) =0    THEN '0.No calificado'
     WHEN (CTA_MISC_CR_SCORE)<=455  THEN '1.VERY HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=525  THEN '2.HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=603  THEN '3.MEDIUM'
     WHEN (CTA_MISC_CR_SCORE)<=661  THEN '4.LOW'
     WHEN (CTA_MISC_CR_SCORE)>661   THEN '5.VERY LOW' 

    END
-- SBB TD 
WHEN  TIP_INF=210 and date(ANIO,MES,1) >= '2022-04-01' THEN 

CASE WHEN (CTA_MISC_CR_SCORE)=0     THEN '0.No calificado'
     WHEN (CTA_MISC_CR_SCORE)<=455  THEN '1.VERY HIGH'  --- INICIA CAMBIO DE NIVEL DE RIESGO
     WHEN (CTA_MISC_CR_SCORE)<=525  THEN '2.HIGH'
     WHEN (CTA_MISC_CR_SCORE)<=603  THEN '3.MEDIUM'
     WHEN (CTA_MISC_CR_SCORE)<=661  THEN '4.LOW'
     WHEN (CTA_MISC_CR_SCORE)>661   THEN '5.VERY LOW' 
     END


WHEN TIP_INF = 200 and date(ANIO,MES,1) >= '2024-02-01' THEN 

CASE WHEN CTA_MISC_CR_SCORE=0     THEN '0.No calificado'
     WHEN CTA_MISC_CR_SCORE<=451  THEN '1.VERY HIGH'
     WHEN CTA_MISC_CR_SCORE<=531  THEN '2.HIGH'
     WHEN CTA_MISC_CR_SCORE<=637  THEN '3.MEDIUM'
     WHEN CTA_MISC_CR_SCORE<=714  THEN '4.LOW'
     WHEN CTA_MISC_CR_SCORE>783   THEN '5.VERY LOW'
     END 
END  AS NIV_RIESGO,
                                        CASE WHEN CTA_STMT_FLG='0' THEN 'IMPRESO'
                                                WHEN CTA_STMT_FLG='1' THEN 'PAPERLESS'
                                                WHEN CTA_STMT_FLG='2' THEN 'PAPERLESS E IMPRESO'
                                        ELSE 'OTRO' END AS FLG_PAPER,

        
        
         
        
        
                               FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES` AS A
                                  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS B ON A.CTA_CVE=B.CTA_CVE --CAMBIO DE LLAVE
                    
                               ) AS B ON ( A.CTA_CVE=B.CTA_TRACK 
                               )
                               
                                WHERE   (((ANIO_OBS - ANIO_ESTR)*12) + (MES_OBS-MES_ESTR))>=0
                                 AND ((a.tip_inf in (110) and CTA_EDO_CVE NOT IN ('T')) OR (A.TIP_INF NOT IN (110)))
                                  
        
                                
                                
              ) 
                                  ),

                                  DISPOSICIONES_FLG AS (

        SELECT A.* , B.FLG_TITU, B.FLG_ADIC, CTE_CVE_UNICO, IMP_INT_MOR, IMP_INT_TOT, IMP_INT_MSI, 
                            CASE WHEN F.CTA_CVE IS NULL THEN '0' ELSE '1' END AS FLG_DIG, 
                            CASE WHEN SEGMENTO_OFICIAL IN (0,099) OR SEGMENTO_OFICIAL IS NULL THEN "No clasificado" ELSE CAST (SEGMENTO_OFICIAL AS STRING) END AS MACROSEGMENTO , 
                            SEGMENTO_CLIENTE, CANT_CAST,IMP_QUITA,CANT_QUITA, IMP_CAST,
                           CASE WHEN (Q.CTA_CVE=0 OR Q.CTA_CVE IS NULL) THEN 0 ELSE 1 END AS FLG_CAST,
                           CASE WHEN (P.CTA_CVE=0 OR P.CTA_CVE IS NULL) THEN 0 ELSE 1 END AS FLG_QUIT,
                            
                             CASE WHEN ((  Q.ANIO-ANIO_ESTR)*12 +(Q.MES-MES_ESTR))<=12 THEN 'Y1'
                                WHEN ((Q.ANIO-ANIO_ESTR)*12 +(Q.MES-MES_ESTR))<=24 THEN 'Y2'
                                WHEN ((Q.ANIO-ANIO_ESTR)*12 +(Q.MES-MES_ESTR))<=36 THEN 'Y3'
                                ELSE 'OTRO' END AS YTD_CAST, 
                            ((Q.ANIO-ANIO_ESTR)*12)+(Q.MES-MES_ESTR) AS MOBS_CAST,
                                CASE WHEN (( I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=12 THEN 'Y1'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=24 THEN 'Y2'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=36 THEN 'Y3'
                                ELSE 'OTRO' END AS YTD_INT,
                            CASE WHEN (( I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=12 THEN 'Y1'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=24 THEN 'Y2'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=36 THEN 'Y3'
                                ELSE 'OTRO' END AS YTD_MSI,
                                IMP_INT_FIN,
                                IMP_COM,
                                CASE WHEN A.TIP_INF=100 AND CVE_NODO=0 THEN 'Sin Minimo'
                                        WHEN ANIOMES_OBS<=202202 AND A.TIP_INF=100 AND CVE_NODO IN (1,2,3,4,5) THEN 'A. 7-48 meses'
                                        WHEN ANIOMES_OBS<=202202 AND A.TIP_INF=100 AND CVE_NODO IN (6,7,8,9) THEN 'B. 49-84 meses'
                                        WHEN ANIOMES_OBS<=202202 AND A.TIP_INF=100 AND CVE_NODO IN (10,11,12,13) THEN 'C. 85+ meses'

                                        WHEN ANIOMES_OBS>=202203 AND A.TIP_INF=100 AND CVE_NODO IN (1,2,3,4,5) THEN 'A. 7-48 meses'
                                        WHEN ANIOMES_OBS>=202203 AND A.TIP_INF=100 AND CVE_NODO IN (6,7,8,9) THEN 'B. 49-84 meses'
                                        WHEN ANIOMES_OBS>=202203 AND A.TIP_INF=100 AND CVE_NODO IN (10,11,12,13) THEN 'C. 85+ meses'

                                        WHEN ANIOMES_OBS<=202203 AND A.TIP_INF=110 AND CVE_NODO IN (1,2,3,4) THEN 'A. 7-35 meses'
                                        WHEN ANIOMES_OBS<=202203 AND A.TIP_INF=110 AND CVE_NODO IN (5,6,7,8) THEN 'B. 36-71 meses'
                                        WHEN ANIOMES_OBS<=202203 AND A.TIP_INF=110 AND CVE_NODO IN (9,10,11,12,13) THEN 'C. 72+ meses'

                                        WHEN ANIOMES_OBS>=202204 AND A.TIP_INF=110 AND CVE_NODO IN (0,1,2,3,4) THEN 'A. 7-35 meses'
                                        WHEN ANIOMES_OBS>=202204 AND A.TIP_INF=110 AND CVE_NODO IN (5,6,7,8,9) THEN 'B. 36-71 meses'
                                        WHEN ANIOMES_OBS>=202204 AND A.TIP_INF=110 AND CVE_NODO IN (10,11,12,13,14,15,16) THEN 'C. 72+ meses'
                                ELSE 'D. Menor a 7 meses' END AS CVE_NODO_RANK_MOB,
                                CASE WHEN  A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)<2010 or CTA_FCH_ALTA IS NULL) THEN '<2009'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2010 AND 2015) THEN '2010 - 2015'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2016 AND 2019) THEN '2016 - 2019'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2020 AND 2020) THEN '2020'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2021 AND 2021) THEN '2021'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2022 AND 2022) THEN '2022'
                                        WHEN A.TIP_INF IN (210,200) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)>=2018) THEN CAST(EXTRACT(YEAR FROM CTA_FCH_ALTA) AS STRING)
                                                ELSE 'NO'
				        END AS RANG_ALTA, 
                                CASE WHEN FLOOR ( ((ANIOMES_OBS) - ((EXTRACT(YEAR FROM CTE_FCH_NAC) *100) + EXTRACT(MONTH FROM CTE_FCH_NAC)) )/100 ) < 0 THEN 0 ELSE FLOOR ( ((ANIOMES_OBS) - ((EXTRACT(YEAR FROM CTE_FCH_NAC)*100)+EXTRACT(MONTH FROM CTE_FCH_NAC)))/100 ) END AS CTE_EDAD,
                                CASE WHEN CTE_GEN=1 THEN 'M' 
                                WHEN CTE_GEN=2 THEN 'F' ELSE '0' END AS SEXO,
                                CASE WHEN A.TIP_INF IN (100,110) THEN D.TDA_ZNA ELSE ZONA_DES END AS TDA_ZNA,/*SEGMENTO_RFM*/

                             FROM DISPOSICIONES AS A

        
        LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_TDA` AS D ON A.CTA_TDA_APE = D.TDA_CVE
        LEFT JOIN (SELECT TDA_CVE, ZONA_DES FROM  `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_NEGFIN_ZONAS_SBB` WHERE FCH_CARGA = (SELECT MAX(FCH_CARGA) FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_NEGFIN_ZONAS_SBB`) )  AS E ON A.CTA_TDA_APE=E.TDA_CVE 
        LEFT JOIN (SELECT  DISTINCT(SAFE_CAST(CARD_NUMBER AS NUMERIC) ) AS CTA_CVE FROM  `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_CTE_MICREDITO` ) AS F ON F.CTA_CVE=A.CTA_CVE 

         LEFT JOIN (SELECT DISTINCT 
                                A.SEGMENTO_OFICIAL,A.CTA_CVE,  EXTRACT (YEAR FROM FEC_MACROSEG) ANIO, 
                                       EXTRACT(MONTH FROM FEC_MACROSEG) AS MES 
                        FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_MACROSEGMENTO` AS A 
                             left join (select cta_cve,EXTRACT (YEAR FROM FEC_MACROSEG) as anio,EXTRACT(MONTH FROM FEC_MACROSEG) as mes, max(FEC_MACROSEG) as maxi
                        from `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_MACROSEGMENTO` group by 1,2,3 ) as b
                        on (a.cta_cve=b.cta_cve  and EXTRACT (YEAR FROM a.FEC_MACROSEG)=b.anio and EXTRACT(MONTH FROM FEC_MACROSEG)=b.mes)
                        where
                        a.FEC_MACROSEG =b.maxi ) AS Y
                          /*Consulta Segmento Cliente*/     
                                    
                        ON(A.CTA_CVE=Y.CTA_CVE AND Y.ANIO=A.ANIO_OBS AND Y.MES=A.MES_OBS)
                         LEFT JOIN (SELECT DISTINCT A.SEGMENTO_CLIENTE,A.CTA_CVE,  ANIO, MES 
                         FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_SEGMENTO_CTE` AS A ) AS W
                               
                                    
                        ON(A.CTA_CVE=W.CTA_CVE AND W.ANIO=A.ANIO_OBS AND W.MES=A.MES_OBS)

                        --LEFT JOIN  (
                        --       SELECT RFM_CREDITO AS SEGMENTO_RFM, ANIO, MES,CASE WHEN (C.CTA_ACT=0 OR C.CTA_ACT IS NULL) THEN A.CTA_CVE ELSE C.CTA_ACT END AS CTA_CVE   FROM  `crp-pro-cx-semantica.mus_pro_shared_views.VDIM_SGMTOS_RFM_HIST_AANF` A 
                        --LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` C ON A.CTA_CVE=C.CTA_CVE
                        --) AS k ON A.CTA_CVE = k.CTA_CVE  AND A.ANIO_OBS=k.ANIO AND A.MES_OBS=k.MES 


                        LEFT JOIN (   
                        SELECT CTA_CVE, TIP_INF, ANIO, MES, SUM(IMP_INT_FIN) AS IMP_INT_FIN, SUM(IMP_INT_MOR) AS IMP_INT_MOR, 
                        SUM(IMP_INT_MOR+ IMP_INT_FIN) AS IMP_INT_TOT, SUM(IMP_INT_MSI) AS IMP_INT_MSI FROM (
                                SELECT CASE WHEN (C.CTA_ACT=0 OR C.CTA_ACT IS NULL) THEN A.CTA_CVE ELSE C.CTA_ACT END AS CTA_CVE, TIP_INF, ANIO, MES, 
                                CASE
                                        WHEN INDICADOR = 'INTERESES_FIN' THEN IMP ELSE 0 END AS IMP_INT_FIN,
                                        CASE
                                        WHEN INDICADOR= 'INTERESES_MOR' THEN IMP ELSE 0 END AS IMP_INT_MOR,
                                CASE       WHEN INDICADOR LIKE '%MSI%' THEN IMP ELSE 0 END AS IMP_INT_MSI
                                FROM
                                        `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_NEGFIN_INTER_MSI` AS A 
                                LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS C ON A.CTA_CVE=C.CTA_CVE
                                WHERE MES= (SELECT EXTRACT(MONTH FROM FCH_FIN) FROM TIEMPO) 
                                AND ANIO= (SELECT EXTRACT(YEAR FROM FCH_FIN) FROM TIEMPO) ) GROUP BY 1, 2, 3, 4             
                                ) AS I ON (A.CTA_CVE=I.CTA_CVE AND A.ANIO_OBS=I.ANIO AND A.MES_OBS=I.MES)


        LEFT JOIN (
                  SELECT CASE WHEN (C.CTA_ACT=0 OR C.CTA_ACT IS NULL) THEN B.CTA_CVE ELSE C.CTA_ACT END AS CTA_CVE
                        ,EXTRACT(YEAR FROM FCH_FCH) AS ANIO 
                        ,EXTRACT(MONTH FROM FCH_FCH) AS MES
                        --,CASE WHEN TRN_CVE IN (502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517) THEN B.TRN_IMP ELSE 0 END AS IMP_CAST
                        ,SUM(TRN_IMP) AS IMP_CAST
                        ,COUNT(CASE WHEN B.TRN_IMP>0 THEN 1 ELSE 0 END) AS CANT_CAST
                  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD` B
                      LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS C ON C.CTA_CVE=B.CTA_CVE
                            WHERE B.FCH_FCH BETWEEN (SELECT FCH_INI FROM TIEMPO) AND (SELECT FCH_FIN FROM TIEMPO)
                                        AND B.TRN_CVE IN (502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517)
                                        GROUP BY 1,2,3
                                ) AS Q ON (Q.CTA_CVE=A.CTA_CVE AND Q.ANIO=A.ANIO_OBS AND Q.MES=A.MES_OBS) 
  LEFT JOIN (
                  SELECT B.CTA_CVE
                        ,CASE WHEN (C.CTA_ACT=0 OR C.CTA_ACT IS NULL) THEN B.CTA_CVE ELSE C.CTA_ACT END AS CTA_TRACK
                        ,EXTRACT(YEAR FROM FCH_FCH) AS ANIO 
                        ,EXTRACT(MONTH FROM FCH_FCH) AS MES
                        --,CASE WHEN TRN_CVE IN (502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517) THEN B.TRN_IMP ELSE 0 END AS IMP_CAST
                        ,SUM(TRN_IMP) AS IMP_QUITA
                        ,COUNT(CASE WHEN B.TRN_IMP>0 THEN 1 ELSE 0 END) AS CANT_QUITA
                  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD` B
                      LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS C ON C.CTA_CVE=B.CTA_CVE
                            WHERE B.FCH_FCH BETWEEN (SELECT FCH_INI FROM TIEMPO) AND (SELECT FCH_FIN FROM TIEMPO)
                                        AND B.TRN_CVE IN (307,407,763,764)
                                        GROUP BY 1,2,3,4
                                ) AS P ON (P.CTA_TRACK=A.CTA_CVE AND P.ANIO=A.ANIO_OBS AND P.MES=A.MES_OBS)


  LEFT JOIN (

        SELECT CTA_CVE, ANIO, MES, SUM (TRN_IMP) AS IMP_COM FROM `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_NEGFIN_TM_COMISIONES` WHERE INDICADOR='COMISION_DISP' GROUP BY 1,2,3
  ) AS O ON A.CTA_CVE= O.CTA_CVE AND A.ANIO_OBS=O.ANIO AND A.MES_OBS=O.MES

  LEFT JOIN (
    SELECT *

    FROM(
         SELECT CTE_FCH_NAC,CTA_CVE, CTE_GEN,  CTE_ID, CTE_CVE_RFC, ROW_NUMBER() OVER(PARTITION BY CTA_CVE order by FCH_CARGA) ORDEN
         FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES`
           WHERE SYS_FTE = 12
    ) AS A

  LEFT JOIN (
        SELECT CTE_ID, CDP FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_DIREC_FTES`) AS B ON A.CTE_ID = B.CTE_ID
    WHERE ORDEN = 1

  ) AS N ON N.CTA_CVE=A.CTA_CVE 
  LEFT JOIN TITULAR AS B ON A.CTA_CVE=B.CTA_CVE
        LEFT JOIN CTE_UNICO AS C ON A.CTA_CVE=C.CTA_CVE       

  ),

  
  
DIM_FINAL AS (
  SELECT A.*, ((ANIO_OBS - ANIO_ESTR)*12) + (MES_OBS-MES_ESTR) AS ANTIG_ESTR, 
                 CASE WHEN CTE_EDAD<30 THEN '30'			
		    WHEN CTE_EDAD>=30 AND CTE_EDAD<35 THEN '30-35'
		    WHEN CTE_EDAD>=35 AND CTE_EDAD<45 THEN '35-45'
		    WHEN CTE_EDAD>=45 AND CTE_EDAD<50 THEN '45-50'
	            WHEN CTE_EDAD>=50 THEN '50+' ELSE 'Sin clasificar' END AS RANGO_EDAD, 
                   
                CASE WHEN (TIP_INF IN (110,100) and TDA_ZNA ="1") THEN "01. Metro Sur"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="2") THEN "02. Metro Norte"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="3") THEN "03. Centro"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="4") THEN "04. Occidente"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="5") THEN "05. Golfo"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="6") THEN "06. Noreste"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="7") THEN "07. Bajio"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="8") THEN "08. Noroeste"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="9") THEN "09. Sureste"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="VAD") THEN "10. Vtas a Distancia"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA NOT IN ("OTRO", "VAD", '1','2','3','4','5','6','7','8','9')) THEN "11. OTRO"
                        WHEN TIP_INF IN (210,200,220) AND CTA_TDA_APE in ("0782", "0039") THEN "15.- ONLINE"
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Centro Norte' THEN '08.- Centro Norte'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Sur' THEN '12.- Sur'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Centro Sur' THEN '10.- Centro Sur'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Centro' THEN '04.- Metro Centro'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Golfo' THEN '11.- Golfo'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Occidente' THEN '06.- Occidente'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Oriente' THEN '02.- Metro Oriente'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Norte' THEN '03.- Metro Norte'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Norte' THEN '09.- Norte'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Sur' THEN '01.- Metro Sur'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Bajio' THEN '05.- Bajio'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Pacifico' THEN '07.- Pacificio'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='VDA' THEN '14.- VAD'
               ELSE '13.- OTRO'
              
               
             END CVE_ZNA,   
             FIRST_VALUE(NIV_RIESGO) OVER(PARTITION BY CTA_CVE,ANIOMES_ESTR ORDER BY ANIOMES_OBS ASC) AS NIV_RIESGO_INI,
              FIRST_VALUE(LOG_CVE) OVER(PARTITION BY CTA_CVE,ANIO_ESTR,MES_ESTR,TIP_INF ORDER BY ANIOMES_ESTR ASC) AS LOG_CVE_INI,
              FIRST_VALUE(CTA_TOTALERO_FLG) OVER(PARTITION BY CTA_CVE,ANIO_ESTR,MES_ESTR,TIP_INF ORDER BY ANIOMES_ESTR ASC) AS CTA_TOTALERO_FLG_INI,
              FIRST_VALUE(CTA_SDO_TOTALERO) OVER(PARTITION BY CTA_CVE,ANIO_ESTR,MES_ESTR,TIP_INF ORDER BY ANIOMES_ESTR ASC) AS CTA_SDO_TOTALERO_FLG_INI,
              FIRST_VALUE(MACROSEGMENTO) OVER(PARTITION BY CTA_CVE,ANIO_ESTR,MES_ESTR,TIP_INF ORDER BY ANIOMES_ESTR ASC) AS MACROSEGMENTO_INI,
                FIRST_VALUE(CTA_EDO_CVE) OVER(PARTITION BY CTA_CVE,ANIO_ESTR,MES_ESTR,TIP_INF ORDER BY ANIOMES_ESTR ASC) AS CTA_EDO_CVE_INI,

        

    FROM DISPOSICIONES_FLG as a 

  --  WHERE ANIOMES_OBS BETWEEN (EXTRACT(YEAR FROM (SELECT FCH_INI FROM TIEMPO))*100)+EXTRACT(MONTH FROM (SELECT FCH_INI FROM TIEMPO)) AND (EXTRACT(YEAR FROM (SELECT FCH_FIN FROM TIEMPO))*100)+EXTRACT(MONTH FROM (SELECT FCH_FIN FROM TIEMPO))
   GROUP BY CTA_CVE
,ANIO_ESTR
,MES_ESTR
,TIP_INF
,CANT_TRN
,IMP_TRN
,ANIO_OBS
,MES_OBS
,FLG_PAPER
,NIV_RIESGO
,RANG_NIV_MOR
,RANG_TASA_RBP
,RANG_UTILIZA
,RANG_SDO_ACT
,CTA_EDO_CVE
,MOBS_ALT
,MOBS_ALT_ESTR
,ANIOMES_ESTR
,ANIOMES_OBS
,CTA_TDA_APE
,CTA_SDO_ACT
,LOG_CVE
,CTA_TASA_RBP
,CTA_NIV_MOR
,CTA_SDO_TOTALERO
,CTA_TOTALERO_FLG
,CTA_FCH_ALTA
,FLG_CANAL
,PLAN_CVE
,FLG_30
,FLG_90
,YTD_ESTR
,CTA_IMP_LIM_CRD
,RANG_LIM_CRD
,COSECHA
,CTA_CON_SDO
,CTA_MISC_CR_SCORE
,PRCT_UTI
,RANG_MOBS
,CVE_NODO
,FLG_TITU
,FLG_ADIC
,CTE_CVE_UNICO
,IMP_INT_MOR
,IMP_INT_TOT
,IMP_INT_MSI
,FLG_DIG
,MACROSEGMENTO
,SEGMENTO_CLIENTE
,CANT_CAST
,IMP_QUITA
,CANT_QUITA
,IMP_CAST
,FLG_CAST
,FLG_QUIT
,YTD_CAST
,MOBS_CAST
,YTD_INT
,YTD_MSI
,IMP_INT_FIN
,IMP_COM
,CVE_NODO_RANK_MOB
,RANG_ALTA
,CTE_EDAD
,SEXO
,TDA_ZNA
,ANTIG_ESTR
,RANGO_EDAD
,CVE_ZNA



)


SELECT * FROM (SELECT CTA_CVE
,ANIO_ESTR
,MES_ESTR
,TIP_INF
,CANT_TRN
,IMP_TRN
,ANIO_OBS
,MES_OBS
,FLG_PAPER
,NIV_RIESGO
,RANG_NIV_MOR
,RANG_TASA_RBP
,RANG_UTILIZA
,RANG_SDO_ACT
,MOBS_ALT
,MOBS_ALT_ESTR
,ANIOMES_ESTR
,ANIOMES_OBS
,CTA_TDA_APE
,CTA_EDO_CVE_INI AS CTA_EDO_CVE
,CTA_SDO_ACT
,LOG_CVE_INI AS LOG_CVE
,CTA_TASA_RBP
,CTA_NIV_MOR
,CTA_SDO_TOTALERO_FLG_INI AS CTA_SDO_TOTALERO
,LOG_CVE_INI AS CTA_TOTALERO_FLG
,CTA_FCH_ALTA
,ANTIG_ESTR
,FLG_CANAL
,PLAN_CVE
,FLG_30
,FLG_90
,YTD_ESTR
,CTA_IMP_LIM_CRD
,RANG_LIM_CRD
,COSECHA
,CTA_CON_SDO
,CTA_MISC_CR_SCORE
,PRCT_UTI
,RANG_MOBS
,CVE_NODO
,FLG_TITU
,FLG_ADIC
,CTE_CVE_UNICO
,IMP_INT_MOR
,IMP_INT_TOT
,IMP_INT_MSI
,FLG_DIG
,MACROSEGMENTO_INI AS MACROSEGMENTO
,SEGMENTO_CLIENTE
,CANT_CAST
,IMP_QUITA
,CANT_QUITA
,IMP_CAST
,FLG_CAST
,FLG_QUIT
,YTD_CAST
,MOBS_CAST
,YTD_INT
,YTD_MSI
,IMP_INT_FIN
,IMP_COM 
,CVE_NODO_RANK_MOB
,RANG_ALTA
,CTE_EDAD
,SEXO
,TDA_ZNA
,RANGO_EDAD
,CVE_ZNA

FROM (SELECT * FROM DIM_FINAL

GROUP BY ALL ORDER BY ANIO_ESTR,MES_ESTR
)
GROUP BY ALL ORDER BY ANIO_ESTR,MES_ESTR
)

)

