/*
AUTOR: aicruz@liverpool.com.mx

DESC: Mantenimiento a tabla maestra de disposiciones

FCH: 2025-06-17
--========================================================================
*/


--########################################################
--#                                                      #
--#           Funcion: BORRA_TEMPORALES_INI              #
--#                                                      #
--########################################################

--#TRUE RPC HISTORICO // FALSE RPC MENSUAL
DECLARE FLG_RPC BOOLEAN;

DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`;
DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_1_TITULAR`;
DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_2_CTE_UNICO`;
DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_3_DIM`;
DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_4_DISP`;
DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_5_DISP_FLG`;
DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_6_DISP_FIN`;

--########################################################
--#                                                      #
--#           CREA TABLA SI NO EXISTE CON DESCRIPCIONES  #
--#                                                      #
--########################################################
CREATE TABLE IF NOT EXISTS `crp-pro-dwh-analiticagold.MUS_PRO_DWH_SAS_TEMP.FAC_NEGFIN_TM_DISPOSICIONES_LT_06`(
  CTA_CVE		NUMERIC  OPTIONS(DESCRIPTION=""),	
  ANIO_ESTR		INTEGER  OPTIONS(DESCRIPTION=""),	
  MES_ESTR		INTEGER  OPTIONS(DESCRIPTION=""),	
  TIP_INF		INTEGER  OPTIONS(DESCRIPTION=""),	
  CANT_TRN		INTEGER  OPTIONS(DESCRIPTION=""),	
  IMP_TRN		NUMERIC  OPTIONS(DESCRIPTION=""),	
  ANIO_OBS		INTEGER  OPTIONS(DESCRIPTION=""),	
  MES_OBS		INTEGER  OPTIONS(DESCRIPTION=""),	
  FLG_PAPER		STRING  OPTIONS(DESCRIPTION=""),	
  NIV_RIESGO		STRING  OPTIONS(DESCRIPTION=""),	
  RANG_NIV_MOR		STRING  OPTIONS(DESCRIPTION=""),	
  RANG_TASA_RBP		STRING  OPTIONS(DESCRIPTION=""),	
  RANG_UTILIZA		STRING  OPTIONS(DESCRIPTION=""),	
  RANG_SDO_ACT		STRING  OPTIONS(DESCRIPTION=""),	
  CTA_EDO_CVE		STRING  OPTIONS(DESCRIPTION=""),	
  MOBS_ALT		INTEGER  OPTIONS(DESCRIPTION=""),	
  MOBS_ALT_ESTR		INTEGER  OPTIONS(DESCRIPTION=""),	
  ANIOMES_ESTR		INTEGER  OPTIONS(DESCRIPTION=""),	
  ANIOMES_OBS		INTEGER  OPTIONS(DESCRIPTION=""),	
  CTA_TDA_APE		STRING  OPTIONS(DESCRIPTION=""),	
  CTA_SDO_ACT		NUMERIC  OPTIONS(DESCRIPTION=""),	
  LOG_CVE		INTEGER  OPTIONS(DESCRIPTION=""),	
  CTA_TASA_RBP		NUMERIC  OPTIONS(DESCRIPTION=""),	
  CTA_NIV_MOR		INTEGER  OPTIONS(DESCRIPTION=""),	
  CTA_SDO_TOTALERO		NUMERIC  OPTIONS(DESCRIPTION=""),	
  CTA_TOTALERO_FLG		INTEGER  OPTIONS(DESCRIPTION=""),	
  CTA_FCH_ALTA		DATE  OPTIONS(DESCRIPTION=""),	
  FLG_CANAL		STRING  OPTIONS(DESCRIPTION=""),	
  PLAN_CVE		INTEGER  OPTIONS(DESCRIPTION=""),	
  FLG_30		INTEGER  OPTIONS(DESCRIPTION=""),	
  FLG_90		INTEGER  OPTIONS(DESCRIPTION=""),	
  YTD_ESTR		STRING  OPTIONS(DESCRIPTION=""),	
  CTA_IMP_LIM_CRD		NUMERIC  OPTIONS(DESCRIPTION=""),	
  RANG_LIM_CRD		STRING  OPTIONS(DESCRIPTION=""),	
  COSECHA		INTEGER  OPTIONS(DESCRIPTION=""),	
  CTA_CON_SDO		INTEGER  OPTIONS(DESCRIPTION=""),	
  CTA_MISC_CR_SCORE		NUMERIC  OPTIONS(DESCRIPTION=""),	
  PRCT_UTI		NUMERIC  OPTIONS(DESCRIPTION=""),	
  RANG_MOBS		STRING  OPTIONS(DESCRIPTION=""),	
  CVE_NODO		INTEGER  OPTIONS(DESCRIPTION=""),	
  FLG_TITU		INTEGER  OPTIONS(DESCRIPTION=""),	
  FLG_ADIC		INTEGER  OPTIONS(DESCRIPTION=""),	
  CTE_CVE_UNICO		NUMERIC  OPTIONS(DESCRIPTION=""),	
  IMP_INT_MOR		NUMERIC  OPTIONS(DESCRIPTION=""),	
  IMP_INT_TOT		NUMERIC  OPTIONS(DESCRIPTION=""),	
  IMP_INT_MSI		NUMERIC  OPTIONS(DESCRIPTION=""),	
  FLG_DIG		STRING  OPTIONS(DESCRIPTION=""),	
  MACROSEGMENTO		STRING  OPTIONS(DESCRIPTION=""),	
  SEGMENTO_CLIENTE		STRING  OPTIONS(DESCRIPTION=""),	
  CANT_CAST		INTEGER  OPTIONS(DESCRIPTION=""),	
  IMP_QUITA		NUMERIC  OPTIONS(DESCRIPTION=""),	
  CANT_QUITA		INTEGER  OPTIONS(DESCRIPTION=""),	
  IMP_CAST		NUMERIC  OPTIONS(DESCRIPTION=""),	
  FLG_CAST		INTEGER  OPTIONS(DESCRIPTION=""),	
  FLG_QUIT		INTEGER  OPTIONS(DESCRIPTION=""),	
  YTD_CAST		STRING  OPTIONS(DESCRIPTION=""),	
  MOBS_CAST		INTEGER  OPTIONS(DESCRIPTION=""),	
  YTD_INT		STRING  OPTIONS(DESCRIPTION=""),	
  YTD_MSI		STRING  OPTIONS(DESCRIPTION=""),	
  IMP_INT_FIN		NUMERIC  OPTIONS(DESCRIPTION=""),	
  IMP_COM		NUMERIC  OPTIONS(DESCRIPTION=""),	
  CVE_NODO_RANK_MOB		STRING  OPTIONS(DESCRIPTION=""),	
  RANG_ALTA		STRING  OPTIONS(DESCRIPTION=""),	
  CTE_EDAD		FLOAT64  OPTIONS(DESCRIPTION=""),	
  SEXO		STRING  OPTIONS(DESCRIPTION=""),	
  TDA_ZNA		STRING  OPTIONS(DESCRIPTION=""),	
  ANTIG_ESTR		INTEGER  OPTIONS(DESCRIPTION=""),	
  RANGO_EDAD		STRING  OPTIONS(DESCRIPTION=""),	
  CVE_ZNA		STRING  OPTIONS(DESCRIPTION=""),	
  FCH_CARGA		DATE  OPTIONS(DESCRIPTION="")
) PARTITION BY FCH_CARGA;




--########################################################
--#                                                      #
--#           Funcion: Crea Temporal de tiempo           #
--#                                                      #
--########################################################
SET FLG_RPC = TRUE;
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`
AS 



SELECT * 
FROM (
    SELECT  
    CASE WHEN (EXTRACT(DAY FROM DATE('2026-07-01')) = 1 AND FLG_RPC = FALSE) THEN DATE_TRUNC(DATE_ADD(DATE('2026-07-01'), INTERVAL -1 DAY), MONTH)
         WHEN (EXTRACT(DAY FROM DATE('2026-07-01')) = 1 AND FLG_RPC = TRUE) THEN DATE('2017-01-01')
        ELSE DATE_TRUNC(DATE('2026-07-01'), MONTH)
        END AS FCH_INI,

    CASE WHEN EXTRACT(DAY FROM DATE('2026-07-01')) = 1 
        THEN LAST_DAY(DATE_ADD(DATE('2026-07-01'), INTERVAL -1 DAY), MONTH)
        ELSE LAST_DAY(DATE('2026-07-01'), MONTH)
        END AS FCH_FIN,

    
    'TM_DISPOSICIONES' AS ESTRATEGIA
);




           
--########################################################
--#                                                      #
--#           Funcion: Crea Temporal_1 TITULAR           #
--#                                                      #
--########################################################
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_1_TITULAR`
AS
( 
SELECT * FROM  (
                SELECT CTA_CVE,
                SUM(CANT_ADIC) AS FLG_ADIC,
                SUM(CANT_TIT) AS FLG_TITU
                FROM (
                        SELECT A.CTA_CVE
                        ,0 AS CANT_TIT
                        ,COUNT((A.TRJ_NUM)) AS CANT_ADIC
                        FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` AS A
                        WHERE IND_TIT IN ('1',' ') 
                        AND A.TRJ_EDO_CVE NOT IN ('A ','B ','C ','E ','F','H ','J ','K ','O ','P ','Q ','S ','U ','X ','Y ','Z')
                        GROUP BY 1
                UNION ALL
                        SELECT B.CTA_CVE
                        ,COUNT((B.TRJ_NUM)) AS CANT_TIT
                        ,0 AS CANT_ADIC
                        FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` AS B
                        WHERE IND_TIT='0'AND 
                        B.TRJ_EDO_CVE NOT IN ('A ','B ','C ','E ','F','H ','J ','K ','O ','P ','Q ','S ','U ','X ','Y ', 'Z')
                        GROUP BY 1
                )GROUP BY 1
    ) 
);

--########################################################
--#                                                      #
--#           Funcion: Crea Temporal_2 CTE_UNICO         #
--#                                                      #
--########################################################
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_2_CTE_UNICO`
AS
SELECT CTA_CVE, CTE_CVE_UNICO 
FROM (SELECT  CTA_CVE, CTE_CVE_UNICO,Row_number() over (partition by B.CTA_CVE ORDER BY B.CTA_CVE) AS REGISTRO
      FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ` as B
) WHERE REGISTRO=1;

--########################################################
--#                                                      #
--#           Funcion: Crea Temporal_2 DIMENSIONAL       #
--#                                                      #
--########################################################
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_3_DIM`
AS
SELECT DISTINCT  A.CTA_CVE, A.TIP_INF,ANIO_ESTR, MES_ESTR,CTA_FCH_ALTA,PLAN_CVE, 
CASE WHEN PLAN_CVE IN (20002) THEN 'ATM' WHEN PLAN_CVE IN (20003) THEN 'POS' WHEN PLAN_CVE IN (20004) THEN 'DIGITAL'  ELSE 'POS' END AS FLG_CANAL,


        
        SUM(CTOS_IMP) AS CANT_TRN,
       SUM(CASE WHEN A.TRN_CVE in (62, 262, 420,1062,1262 ) THEN TRN_IMP*-1             
                WHEN (A.TRN_CVE in (2,102,122,320,1002,1102,2002,2102) ) THEN TRN_IMP         
                WHEN (/*TRN_CVE  IN (789,339)*/ PLAN_CVE IN (20003,20004) and a.TRN_CVE  in (12,122) AND A.TIP_INF IN (200, 210) ) THEN TRN_IMP
                WHEN (/*TRN_CVE  IN (789,339)*/  PLAN_CVE IN (20003) and a.TRN_CVE  in (72,282) AND A.TIP_INF IN (200, 210) ) THEN TRN_IMP*-1						
          ELSE 0 END) AS IMP_TRN,
FROM (
            SELECT  CTA_CVE, A.TIP_INF, EXTRACT (YEAR FROM A.FCH_FCH) AS ANIO_ESTR,
                    EXTRACT (MONTH FROM A.FCH_FCH) AS MES_ESTR,  A.TRN_CVE,PLAN_CVE ,
                    
                    CASE WHEN (A.TRN_CVE IN (2,102,320,122) AND A.TIP_INF =110) THEN  1 
                        WHEN (A.TRN_CVE IN (2,102,320,1002,1102,2002,2102,122) AND A.TIP_INF =100) THEN 1
                            WHEN (PLAN_CVE IN (20003,20004) and a.TRN_CVE  in (12,122) AND A.TIP_INF IN (200, 210) ) THEN 1
                    ELSE 0 END AS CTOS_IMP, 
                    A.TRN_IMP,
                
            FROM (
                        SELECT   CASE WHEN (C.CTA_ACT IS NULL OR C.CTA_ACT=0) THEN A.CTA_CVE ELSE C.CTA_ACT END CTA_CVE, A.TIP_INF, FCH_FCH, TRN_CVE, TRN_IMP, TDA_CVE,PLAN_CVE--,CTA_NIV_MOR
                        FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD` AS A 
                            LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS C ON A.CTA_CVE=C.CTA_CVE

                        WHERE FCH_FCH BETWEEN (SELECT FCH_INI FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) AND (SELECT FCH_FIN FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`)
                            AND TRN_CVE IN (420,2,62,102,262,320,1002,1062,1102,1262,2002,2102,022,282,122,72,12)
                            AND TIP_INF IN (100, 110,210,200)
                            AND PLAN_CVE IN (20002,20004,20003)
                ) AS A	
        ) AS A
LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` AS C ON A.CTA_CVE=C.CTA_CVE
GROUP BY 1,2,3,4,5,6;


-- ########################################################
-- #                                                      #
-- #                        DISPOSICIONES                 #
-- #                                                      #
-- ########################################################
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_4_DISP`
AS
 SELECT A.CTA_CVE,
    ANIO_ESTR,
    MES_ESTR,
    A.TIP_INF,
    CANT_TRN,
    IMP_TRN,
    ANIO_OBS,
    MES_OBS,
    FLG_PAPER,
    NIV_RIESGO,
    RANG_NIV_MOR,
    RANG_TASA_RBP,
    RANG_UTILIZA,
    RANG_SDO_ACT,
    CTA_EDO_CVE,
    ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) AS MOBS_ALT,
    (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA))) AS MOBS_ALT_ESTR, 
    ((A.ANIO_ESTR*100)+A.MES_ESTR) AS ANIOMES_ESTR,
    ((B.ANIO_OBS*100)+B.MES_OBS) AS ANIOMES_OBS, 
    CTA_TDA_APE, 
    CTA_SDO_ACT,
    B.LOG_CVE,
    CTA_TASA_RBP,
    CTA_NIV_MOR,
    CTA_SDO_TOTALERO,
    CTA_TOTALERO_FLG,
    A.CTA_FCH_ALTA,
    FLG_CANAL, 
    PLAN_CVE,  
    CASE WHEN CTA_NIV_MOR IN (3,4,5,6,7,8,9)  THEN 1 ELSE 0 END AS FLG_30,
    CASE WHEN CTA_NIV_MOR IN (5,6,7,8,9) THEN 1 ELSE 0 END AS FLG_90,
    
    CASE WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=12 THEN 'Y1' 
                                    WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=24 THEN 'Y2'
                                    WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=36 THEN 'Y3'
                                    WHEN (((B.ANIO_OBS-A.ANIO_ESTR)*12)+(B.MES_OBS-A.MES_ESTR))<=48 THEN 'Y4'
                            ELSE 'OTRO' END AS YTD_ESTR,
                            B.CTA_IMP_LIM_CRD,
                            CASE WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 4000 THEN '1.-4,000'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 7500 THEN '2.-4,000-7,499'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 10000 THEN '3.-7,500-9,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 15000 THEN '4.-10,000-14,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 20000 THEN '5.-15,000-19,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 30000 THEN '6.-20,000-29,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD < 50000 THEN '7.-30,000-49,999'
                                    WHEN A.TIP_INF IN (100,110) AND B.CTA_IMP_LIM_CRD >= 50000 THEN '50,000+'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 2000 THEN '1.-0-1,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 4000 THEN '2.-2,000-3,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 8000 THEN '3.-4,000-7,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 12000 THEN '4.-8,000-11,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 15000 THEN '5.-12,000 -14,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 18000 THEN '6.-15,000-17,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD < 20000 THEN '7.-18,000-19,999'
                                    WHEN A.TIP_INF IN (200,210) AND B.CTA_IMP_LIM_CRD >= 20000 THEN '>=20,000'
                            ELSE 'OTRO' END AS RANG_LIM_CRD, 
                            CASE WHEN ANIO_ESTR<2009 THEN 2009 ELSE ((ANIO_ESTR*100)+MES_ESTR) END AS COSECHA,
                             CASE WHEN B.CTA_SDO_ACT>0 THEN 1 ELSE 0 END AS CTA_CON_SDO,
                             CTA_MISC_CR_SCORE,
                           
                            CASE WHEN B.CTA_IMP_LIM_CRD<=0 THEN -1 ELSE B.CTA_SDO_ACT/B.CTA_IMP_LIM_CRD END AS PRCT_UTI,
       
    
        CASE WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=6 THEN 'A.0M-6M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=12 THEN 'B.7M-12M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=24 THEN 'C.13M-24M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=36 THEN 'D.25M-36M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=48 THEN 'E.37M-48M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) <=60 THEN 'F.49M-60M'
             WHEN ((B.ANIO_OBS-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_OBS-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)) >=61 THEN 'G.61M+'

        ELSE '0.- NO CLASIFICADO' END AS RANG_MOBS,


        
                        CASE WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE BETWEEN 406 AND 417 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=436 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=449 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=463 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE>=464 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<406 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE BETWEEN 406 AND 417 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=436 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=449 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE>=450 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<406 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE BETWEEN 400 AND 419 THEN 10
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=435 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=444 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE>=445 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202202 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<400 THEN 0

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE BETWEEN 382 AND 418 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=477 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=527 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<=590 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE>=591 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=48 AND B.CTA_MISC_CR_SCORE<382 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE BETWEEN 382 AND 418 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=477 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<=527 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE>=528 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=84 AND B.CTA_MISC_CR_SCORE<382 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE BETWEEN 368 AND 423 THEN 10
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=474 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<=508 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE>=509 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202203 AND B.TIP_INF=100 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=85 AND B.CTA_MISC_CR_SCORE<368 THEN 0

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE BETWEEN 840 AND 859 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=883 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=889 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE>=890 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<840 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE BETWEEN 840 AND 859 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=883 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=933 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE>=934 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<840 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=819 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=833 THEN 10
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=883 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=917 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE>=918 THEN 13 
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202203 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<800 THEN 0 

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 17
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 443 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=526 THEN 2
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<=553 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE>=554 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=35 AND B.CTA_MISC_CR_SCORE<375 THEN 0
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 443 THEN 6
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=526 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<=704 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE>=705 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=71 AND B.CTA_MISC_CR_SCORE<375 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 413 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=460 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=480 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=540 THEN 14
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<=583 THEN 15
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE>=584 THEN 16 
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)<=202206 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>=72 AND B.CTA_MISC_CR_SCORE<375 THEN 10 

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=6 THEN 15

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=12 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 1
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=12 AND B.CTA_MISC_CR_SCORE>=526 THEN 2

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE<375 THEN 3
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 4
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE BETWEEN 526 AND 603 THEN 5
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=24 AND B.CTA_MISC_CR_SCORE>=604 THEN 6

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE<375 THEN 7
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 8
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE BETWEEN 526 AND 603 THEN 9
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))<=72 AND B.CTA_MISC_CR_SCORE>=604 THEN 10

                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE<375 THEN 11
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE BETWEEN 375 AND 525 THEN 12
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE BETWEEN 526 AND 603 THEN 13
                        WHEN ((B.ANIO_OBS*100)+B.MES_OBS)>=202207 AND B.TIP_INF=110 AND B.LOG_CVE IN (100,120,300,500,600,200) AND (((A.ANIO_ESTR-EXTRACT(YEAR FROM A.CTA_FCH_ALTA))*12)+(MES_ESTR-EXTRACT(MONTH FROM A.CTA_FCH_ALTA)))>72 AND B.CTA_MISC_CR_SCORE>=604 THEN 14

                        END AS CVE_NODO, 
                        
                        
  FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_3_DIM` AS A
  LEFT JOIN ( 
            SELECT DISTINCT A.TIP_INF,      CASE WHEN (A.CTA_CVE IS NULL OR A.CTA_CVE=0) THEN B.CTA_ACT ELSE A.CTA_CVE END CTA_CVE,A.ANIO AS ANIO_OBS,A.MES AS MES_OBS,CTA_TDA_APE,  CTA_IMP_LIM_CRD, CTA_SDO_ACT,
                    A.CTA_EDO_CVE, 
                    CTA_NVO_FACTOR_TASA AS CTA_TASA_RBP,
                    CTA_NIV_MOR,  CTA_FCH_ULT_PAG,
                    CTA_IMP_ULT_PAGO, CTA_SDO_TOTALERO, CTA_TOTALERO_FLG, CTA_FCH_PRM_CMP,
                    CTA_TASA_FLG AS CTA_TASA_RBP_FLG, CTA_MISC_CR_SCORE, a.LOG_CVE,
                    CASE WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 4000 THEN '1.-4,000'
                        WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 7500 THEN '2.-4,000-7,499'
                        WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 10000 THEN '3.-7,500-9,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 15000 THEN '4.-10,000-14,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 20000 THEN '5.-15,000-19,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 30000 THEN '6.-20,000-29,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 50000 THEN '7.-30,000-49,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD >= 50000 THEN '8.-50,000+'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 2000 THEN '1.-0-1,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 4000 THEN '2.-2,000-3,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 8000 THEN '3.-4,000-7,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 12000 THEN '4.-8,000-11,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 15000 THEN '5.-12,000 -14,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 18000 THEN '6.-15,000-17,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 20000 THEN '7.-18,000-19,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD >= 20000 THEN '8.->=20,000'
                    ELSE 'OTRO' END AS RANG_LIM_CRD,
                CASE WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 4000 THEN '1.-4,000'
                        WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 7500 THEN '2.-4,000-7,499'
                        WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 10000 THEN '3.-7,500-9,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 15000 THEN '4.-10,000-14,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 20000 THEN '5.-15,000-19,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 30000 THEN '6.-20,000-29,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT < 50000 THEN '7.-30,000-49,999'
                        WHEN A.TIP_INF IN (100,110) AND CTA_SDO_ACT >= 50000 THEN '8.-50,000+'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 2000 THEN '1.-0-1,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 4000 THEN '2.-2,000-3,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 8000 THEN '3.-4,000-7,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 12000 THEN '4.-8,000-11,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 15000 THEN '5.-12,000 -14,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 18000 THEN '6.-15,000-17,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT < 20000 THEN '7.-18,000-19,999'
                        WHEN A.TIP_INF IN (200,210) AND CTA_SDO_ACT >= 20000 THEN '8.->=20,000'
                ELSE 'OTRO' END RANG_SDO_ACT,
                CASE WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.20 THEN 'A.1-20'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.25 THEN 'B.21-25'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.30 THEN 'C.26-30'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.35 THEN 'D.31-35'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.40 THEN 'E.36-40'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.45 THEN 'F.41-45'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.50 THEN 'G.46-50'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.75 THEN 'H.51-75'
                        WHEN (CASE WHEN CTA_IMP_LIM_CRD<=0 THEN -1 ELSE CTA_SDO_ACT/CTA_IMP_LIM_CRD END)<=.85 THEN 'I.76-85'
                ELSE 'J.86+' END AS RANG_UTILIZA,
            CASE WHEN CTA_NVO_FACTOR_TASA=14.99 AND A.TIP_INF NOT IN (200,210) THEN 'T0'
                    WHEN CTA_NVO_FACTOR_TASA=26.55 AND A.TIP_INF NOT IN (200,210) THEN 'Empleado'
                    WHEN CTA_NVO_FACTOR_TASA=31.39 AND A.TIP_INF NOT IN (200,210) THEN 'T1'
                    WHEN CTA_NVO_FACTOR_TASA=42.04 AND A.TIP_INF NOT IN (200,210) THEN 'T2'
                    WHEN CTA_NVO_FACTOR_TASA=53.11 AND A.TIP_INF NOT IN (200,210) THEN 'T3'
                    WHEN CTA_NVO_FACTOR_TASA=61.2 AND A.TIP_INF NOT IN (200,210) THEN 'T4'
                    WHEN CTA_NVO_FACTOR_TASA=66 AND A.TIP_INF NOT IN (200,210) THEN 'T5'
                    WHEN CTA_NVO_FACTOR_TASA=38.71 AND A.TIP_INF NOT IN (100,110) THEN 'Empleado'
                    WHEN CTA_NVO_FACTOR_TASA=77.42 AND A.TIP_INF NOT IN (100,110) THEN 'T3'
                    WHEN CTA_NVO_FACTOR_TASA=80 AND A.TIP_INF NOT IN (100,110) THEN 'T4'
                    WHEN CTA_NVO_FACTOR_TASA=85 AND A.TIP_INF NOT IN (100,110) THEN 'T5'
            ELSE 'OTRO' END AS RANG_TASA_RBP,
            CASE WHEN CTA_NIV_MOR IN (0,1) THEN '0.-CTAS_VIG'
                    WHEN CTA_NIV_MOR=2 THEN '1.-1-29 DIAS'
                    WHEN CTA_NIV_MOR=3 THEN '2.-30_DIAS'
                    WHEN CTA_NIV_MOR=4 THEN '3.-60_DIAS'
                    WHEN CTA_NIV_MOR=5 THEN '4.-90_DIAS'
                    WHEN CTA_NIV_MOR=6 THEN '5.-120_DIAS'
                    WHEN CTA_NIV_MOR=7 THEN '6.-150_DIAS'
                    WHEN CTA_NIV_MOR=8 THEN '7.-180_DIAS'
            ELSE '8.-210_DIAS' END AS RANG_NIV_MOR,
            CASE    WHEN A.TIP_INF IN (100,110,210,200) AND CTA_MISC_CR_SCORE<=0 THEN '0.NO CALIFICADO'
                    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=405 AND ((ANIO*100)+MES)<=202201 THEN '1.VERY HIGH'
                    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=426 AND ((ANIO*100)+MES)<=202201 THEN '2.HIGH'
                    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=450 AND ((ANIO*100)+MES)<=202201 THEN '3.MEDIUM'
                    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=467 AND ((ANIO*100)+MES)<=202201 THEN '4.LOW'
                    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE>=468 AND ((ANIO*100)+MES)<=202201 THEN '5.VERY LOW'

                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=856 AND ((ANIO*100)+MES)<=202203 THEN '1.VERY HIGH'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=894 AND ((ANIO*100)+MES)<=202203 THEN '2.HIGH'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=929 AND ((ANIO*100)+MES)<=202203 THEN '3.MEDIUM'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=952 AND ((ANIO*100)+MES)<=202203 THEN '4.LOW'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE>=953 AND ((ANIO*100)+MES)<=202203 THEN '5.VERY LOW' 

					--***********************************************************************************************************************--
					--Se genero un cambio en el periodo de evaluación del mes de febrero 2026.
					--***********************************************************************************************************************--
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=455 AND ((ANIO*100)+MES)>=202202 AND ((ANIO*100)+MES)<202602 THEN '1.VERY HIGH' -- AGREGAMOS PERIODO DE EVALUACIÓN
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=525 AND ((ANIO*100)+MES)>=202202 AND ((ANIO*100)+MES)<202602 THEN '2.HIGH'      -- AGREGAMOS PERIODO DE EVALUACIÓN
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=603 AND ((ANIO*100)+MES)>=202202 AND ((ANIO*100)+MES)<202602 THEN '3.MEDIUM'    -- AGREGAMOS PERIODO DE EVALUACIÓN
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=661 AND ((ANIO*100)+MES)>=202202 AND ((ANIO*100)+MES)<202602 THEN '4.LOW'       -- AGREGAMOS PERIODO DE EVALUACIÓN
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE>661 AND ((ANIO*100)+MES)>=202202 AND ((ANIO*100)+MES)<202602 THEN '5.VERY LOW'   -- AGREGAMOS PERIODO DE EVALUACIÓN

                    --WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=455 AND ((ANIO*100)+MES)>=202202 THEN '1.VERY HIGH'
                    --WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=525 AND ((ANIO*100)+MES)>=202202 THEN '2.HIGH'
                    --WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=603 AND ((ANIO*100)+MES)>=202202 THEN '3.MEDIUM'
                    --WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<=661 AND ((ANIO*100)+MES)>=202202 THEN '4.LOW'
                    --WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE>661 AND ((ANIO*100)+MES)>=202202 THEN '5.VERY LOW'

                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=455 AND ((ANIO*100)+MES)>=202204 THEN '1.VERY HIGH'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=525 AND ((ANIO*100)+MES)>=202204 THEN '2.HIGH'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=603 AND ((ANIO*100)+MES)>=202204 THEN '3.MEDIUM'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE<=661 AND ((ANIO*100)+MES)>=202204 THEN '4.LOW'
                    WHEN A.TIP_INF=110 AND CTA_MISC_CR_SCORE>661 AND ((ANIO*100)+MES)>=202204 THEN '5.VERY LOW' 
					
				    --***********************************************************************************************************************--
				    --Se integro esta nueva cascada de opciones a evaluar  que aplica a partir del cierre mensual de febrero 2026.
				    --***********************************************************************************************************************--
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<438 AND ((ANIO*100)+MES)>=202602 THEN '1.VERY HIGH'
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<519 AND ((ANIO*100)+MES)>=202602 THEN '2.HIGH'
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<567 AND ((ANIO*100)+MES)>=202602 THEN '3.MEDIUM'
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE<654 AND ((ANIO*100)+MES)>=202602 THEN '4.LOW'
				    WHEN A.TIP_INF=100 AND CTA_MISC_CR_SCORE>=654 AND ((ANIO*100)+MES)>=202602 THEN '5.VERY LOW'

                    WHEN A.TIP_INF=210 AND CTA_MISC_CR_SCORE<=455 AND ((ANIO*100)+MES)>=202204 THEN '1.VERY HIGH'  --- INICIA CAMBIO DE NIVEL DE RIESGO
                    WHEN A.TIP_INF=210 AND CTA_MISC_CR_SCORE<=525 AND ((ANIO*100)+MES)>=202204 THEN '2.HIGH'
                    WHEN A.TIP_INF=210 AND CTA_MISC_CR_SCORE<=603 AND ((ANIO*100)+MES)>=202204 THEN '3.MEDIUM'
                    WHEN A.TIP_INF=210 AND CTA_MISC_CR_SCORE<=661 AND ((ANIO*100)+MES)>=202204 THEN '4.LOW'
                    WHEN A.TIP_INF=210 AND CTA_MISC_CR_SCORE>661 AND ((ANIO*100)+MES)>=202204 THEN '5.VERY LOW' 

                    WHEN A.TIP_INF=200 AND CTA_MISC_CR_SCORE<=451 AND ((ANIO*100)+MES)>=202402 THEN '1.VERY HIGH'
                    WHEN A.TIP_INF=200 AND CTA_MISC_CR_SCORE<=531 AND ((ANIO*100)+MES)>=202402 THEN '2.HIGH'
                    WHEN A.TIP_INF=200 AND CTA_MISC_CR_SCORE<=637 AND ((ANIO*100)+MES)>=202402 THEN '3.MEDIUM'
                    WHEN A.TIP_INF=200 AND CTA_MISC_CR_SCORE<=714 AND ((ANIO*100)+MES)>=202402 THEN '4.LOW'
                    WHEN A.TIP_INF=200 AND CTA_MISC_CR_SCORE>783 AND ((ANIO*100)+MES)>=202402 THEN '5.VERY LOW'  -- TERMINA CAMBIO DE NIVEL DE RIESGO
                    
            END AS NIV_RIESGO,
            CASE WHEN CTA_STMT_FLG='0' THEN 'IMPRESO'
                    WHEN CTA_STMT_FLG='1' THEN 'PAPERLESS'
                    WHEN CTA_STMT_FLG='2' THEN 'PAPERLESS E IMPRESO'
            ELSE 'OTRO' END AS FLG_PAPER,  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES` AS A

            LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS B ON A.CTA_CVE=B.CTA_CVE --CAMBIO DE LLAVE
            ) B ON A.CTA_CVE=B.CTA_CVE
            LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` AS C ON A.CTA_CVE=C.CTA_CVE
            --CAMBIO DE LLAVE
            WHERE   (((ANIO_OBS - ANIO_ESTR)*12) + (MES_OBS-MES_ESTR))>=0;

-- ########################################################
-- #                                                      #
-- #                        DISPOSICIONES_FLG             #
-- #                                                      #
-- ########################################################

SET FLG_RPC = TRUE; --AQUI SE DESACTIVA EL MODO HISTORIA

--########################################################
--#                                                      #
--#           Funcion: Crea Temporal de tiempo           #
--#                                                      #
--########################################################
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`
AS 



SELECT * 
FROM (
    SELECT  
    CASE WHEN (EXTRACT(DAY FROM DATE('2026-07-01')) = 1 AND FLG_RPC = FALSE) THEN DATE_TRUNC(DATE_ADD(DATE('2026-07-01'), INTERVAL -1 DAY), MONTH)
         WHEN (EXTRACT(DAY FROM DATE('2026-07-01')) = 1 AND FLG_RPC = TRUE) THEN DATE('2017-01-01')
        ELSE DATE_TRUNC(DATE('2026-07-01'), MONTH)
        END AS FCH_INI,

    CASE WHEN EXTRACT(DAY FROM DATE('2026-07-01')) = 1 
        THEN LAST_DAY(DATE_ADD(DATE('2026-07-01'), INTERVAL -1 DAY), MONTH)
        ELSE LAST_DAY(DATE('2026-07-01'), MONTH)
        END AS FCH_FIN,

    
    'TM_DISPOSICIONES' AS ESTRATEGIA
);


CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_5_DISP_FLG`
AS
SELECT A.* , B.FLG_TITU, B.FLG_ADIC, CTE_CVE_UNICO, IMP_INT_MOR, IMP_INT_TOT, IMP_INT_MSI, 
                            CASE WHEN F.CTA_CVE IS NULL THEN '0' ELSE '1' END AS FLG_DIG, 
                            CASE WHEN SEGMENTO_OFICIAL IN (0,099) OR SEGMENTO_OFICIAL IS NULL THEN "No clasificado" ELSE CAST (SEGMENTO_OFICIAL AS STRING) END AS MACROSEGMENTO , 
                            SEGMENTO_CLIENTE, CANT_CAST,IMP_QUITA,CANT_QUITA, IMP_CAST,
                           CASE WHEN (Q.CTA_CVE=0 OR Q.CTA_CVE IS NULL) THEN 0 ELSE 1 END AS FLG_CAST,
                           CASE WHEN (P.CTA_CVE=0 OR P.CTA_CVE IS NULL) THEN 0 ELSE 1 END AS FLG_QUIT,
                            
                             CASE WHEN ((  Q.ANIO-ANIO_ESTR)*12 +(Q.MES-MES_ESTR))<=12 THEN 'Y1'
                                WHEN ((Q.ANIO-ANIO_ESTR)*12 +(Q.MES-MES_ESTR))<=24 THEN 'Y2'
                                WHEN ((Q.ANIO-ANIO_ESTR)*12 +(Q.MES-MES_ESTR))<=36 THEN 'Y3'
                                ELSE 'OTRO' END AS YTD_CAST, 
                            ((Q.ANIO-ANIO_ESTR)*12)+(Q.MES-MES_ESTR) AS MOBS_CAST,
                                CASE WHEN (( I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=12 THEN 'Y1'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=24 THEN 'Y2'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=36 THEN 'Y3'
                                ELSE 'OTRO' END AS YTD_INT,
                            CASE WHEN (( I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=12 THEN 'Y1'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=24 THEN 'Y2'
                                WHEN ((I.ANIO-ANIO_ESTR)*12 +(I.MES-MES_ESTR))<=36 THEN 'Y3'
                                ELSE 'OTRO' END AS YTD_MSI,
                                IMP_INT_FIN,
                                IMP_COM,
                                CASE WHEN A.TIP_INF=100 AND CVE_NODO=0 THEN 'Sin Minimo'
                                        WHEN ANIOMES_OBS<=202202 AND A.TIP_INF=100 AND CVE_NODO IN (1,2,3,4,5) THEN 'A. 7-48 meses'
                                        WHEN ANIOMES_OBS<=202202 AND A.TIP_INF=100 AND CVE_NODO IN (6,7,8,9) THEN 'B. 49-84 meses'
                                        WHEN ANIOMES_OBS<=202202 AND A.TIP_INF=100 AND CVE_NODO IN (10,11,12,13) THEN 'C. 85+ meses'

                                        WHEN ANIOMES_OBS>=202203 AND A.TIP_INF=100 AND CVE_NODO IN (1,2,3,4,5) THEN 'A. 7-48 meses'
                                        WHEN ANIOMES_OBS>=202203 AND A.TIP_INF=100 AND CVE_NODO IN (6,7,8,9) THEN 'B. 49-84 meses'
                                        WHEN ANIOMES_OBS>=202203 AND A.TIP_INF=100 AND CVE_NODO IN (10,11,12,13) THEN 'C. 85+ meses'

                                        WHEN ANIOMES_OBS<=202203 AND A.TIP_INF=110 AND CVE_NODO IN (1,2,3,4) THEN 'A. 7-35 meses'
                                        WHEN ANIOMES_OBS<=202203 AND A.TIP_INF=110 AND CVE_NODO IN (5,6,7,8) THEN 'B. 36-71 meses'
                                        WHEN ANIOMES_OBS<=202203 AND A.TIP_INF=110 AND CVE_NODO IN (9,10,11,12,13) THEN 'C. 72+ meses'

                                        WHEN ANIOMES_OBS>=202204 AND A.TIP_INF=110 AND CVE_NODO IN (0,1,2,3,4) THEN 'A. 7-35 meses'
                                        WHEN ANIOMES_OBS>=202204 AND A.TIP_INF=110 AND CVE_NODO IN (5,6,7,8,9) THEN 'B. 36-71 meses'
                                        WHEN ANIOMES_OBS>=202204 AND A.TIP_INF=110 AND CVE_NODO IN (10,11,12,13,14,15,16) THEN 'C. 72+ meses'
                                ELSE 'D. Menor a 7 meses' END AS CVE_NODO_RANK_MOB,
                                CASE WHEN  A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)<2010 or CTA_FCH_ALTA IS NULL) THEN '<2009'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2010 AND 2015) THEN '2010 - 2015'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2016 AND 2019) THEN '2016 - 2019'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2020 AND 2020) THEN '2020'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2021 AND 2021) THEN '2021'
                                        WHEN A.TIP_INF IN (110,100) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)BETWEEN 2022 AND 2022) THEN '2022'
                                        WHEN A.TIP_INF IN (210,200) AND (EXTRACT(YEAR FROM CTA_FCH_ALTA)>=2018) THEN CAST(EXTRACT(YEAR FROM CTA_FCH_ALTA) AS STRING)
                                                ELSE 'NO'
				        END AS RANG_ALTA, 
                                CASE WHEN FLOOR ( ((ANIOMES_OBS) - ((EXTRACT(YEAR FROM CTE_FCH_NAC) *100) + EXTRACT(MONTH FROM CTE_FCH_NAC)) )/100 ) < 0 THEN 0 ELSE FLOOR ( ((ANIOMES_OBS) - ((EXTRACT(YEAR FROM CTE_FCH_NAC)*100)+EXTRACT(MONTH FROM CTE_FCH_NAC)))/100 ) END AS CTE_EDAD,
                                CASE WHEN CTE_GEN=1 THEN 'M' 
                                WHEN CTE_GEN=2 THEN 'F' ELSE '0' END AS SEXO,
                                CASE WHEN A.TIP_INF IN (100,110) THEN D.TDA_ZNA ELSE ZONA_DES END AS TDA_ZNA,/*SEGMENTO_RFM*/

                             FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_4_DISP` AS A

        
        LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_TDA` AS D ON A.CTA_TDA_APE = D.TDA_CVE
        LEFT JOIN (SELECT TDA_CVE, ZONA_DES FROM  `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_NEGFIN_ZONAS_SBB` WHERE FCH_CARGA = (SELECT MAX(FCH_CARGA) FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_NEGFIN_ZONAS_SBB`) )  AS E ON A.CTA_TDA_APE=E.TDA_CVE 
        LEFT JOIN (SELECT  DISTINCT(SAFE_CAST(CARD_NUMBER AS NUMERIC) ) AS CTA_CVE FROM  `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_CTE_MICREDITO` ) AS F ON F.CTA_CVE=A.CTA_CVE 

         LEFT JOIN (SELECT DISTINCT 
                                A.SEGMENTO_OFICIAL,A.CTA_CVE,  EXTRACT (YEAR FROM FEC_MACROSEG) ANIO, 
                                       EXTRACT(MONTH FROM FEC_MACROSEG) AS MES 
                        FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_MACROSEGMENTO` AS A 
                             left join (select cta_cve,EXTRACT (YEAR FROM FEC_MACROSEG) as anio,EXTRACT(MONTH FROM FEC_MACROSEG) as mes, max(FEC_MACROSEG) as maxi
                        from `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_MACROSEGMENTO` group by 1,2,3 ) as b
                        on (a.cta_cve=b.cta_cve  and EXTRACT (YEAR FROM a.FEC_MACROSEG)=b.anio and EXTRACT(MONTH FROM FEC_MACROSEG)=b.mes)
                        where
                        a.FEC_MACROSEG =b.maxi ) AS Y
                          /*Consulta Segmento Cliente*/     
                                    
                        ON(A.CTA_CVE=Y.CTA_CVE AND Y.ANIO=A.ANIO_OBS AND Y.MES=A.MES_OBS)
                         LEFT JOIN (SELECT DISTINCT A.SEGMENTO_CLIENTE,A.CTA_CVE,  ANIO, MES 
                         FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_SEGMENTO_CTE` AS A ) AS W
                               
                                    
                        ON(A.CTA_CVE=W.CTA_CVE AND W.ANIO=A.ANIO_OBS AND W.MES=A.MES_OBS)


                        LEFT JOIN (   
                                SELECT CTA_CVE, TIP_INF, ANIO, MES, SUM(IMP_INT_FIN) AS IMP_INT_FIN, SUM(IMP_INT_MOR) AS IMP_INT_MOR, 
                                SUM(IMP_INT_MOR+ IMP_INT_FIN) AS IMP_INT_TOT, SUM(IMP_INT_MSI) AS IMP_INT_MSI FROM (
                                        SELECT CASE WHEN (C.CTA_ACT=0 OR C.CTA_ACT IS NULL) THEN A.CTA_CVE ELSE C.CTA_ACT END AS CTA_CVE, TIP_INF, ANIO, MES, 
                                        CASE
                                                WHEN INDICADOR = 'INTERESES_FIN' THEN IMP ELSE 0 END AS IMP_INT_FIN,
                                                CASE
                                                WHEN INDICADOR= 'INTERESES_MOR' THEN IMP ELSE 0 END AS IMP_INT_MOR,
                                        CASE       WHEN INDICADOR LIKE '%MSI%' THEN IMP ELSE 0 END AS IMP_INT_MSI
                                        FROM
                                                `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_NEGFIN_INTER_MSI` AS A 
                                        LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS C ON A.CTA_CVE=C.CTA_CVE
                                        --WHERE MES= (SELECT EXTRACT(MONTH FROM FCH_INI) FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) 
                                        --AND ANIO= (SELECT EXTRACT(YEAR FROM FCH_INI) FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) ) 
                                        WHERE (
                                                (CAST(ANIO * 100 +  MES AS INT64)) 
                                                
                                                BETWEEN 
                                                (SELECT CAST(EXTRACT(YEAR FROM FCH_INI) * 100 + EXTRACT(MONTH FROM FCH_INI) AS INT64) 
                                                FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) 

                                                AND

                                                (SELECT CAST(EXTRACT(YEAR FROM FCH_FIN) * 100 + EXTRACT(MONTH FROM FCH_FIN) AS INT64) 
                                                FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`)
                                        ))
                                         
                                         -- REGRESAR AQUI
                                        
                                        GROUP BY 1, 2, 3, 4             
                                        ) AS I ON (A.CTA_CVE=I.CTA_CVE AND A.ANIO_OBS=I.ANIO AND A.MES_OBS=I.MES)


        LEFT JOIN (
                  SELECT CASE WHEN (C.CTA_ACT=0 OR C.CTA_ACT IS NULL) THEN B.CTA_CVE ELSE C.CTA_ACT END AS CTA_CVE
                        ,EXTRACT(YEAR FROM FCH_FCH) AS ANIO 
                        ,EXTRACT(MONTH FROM FCH_FCH) AS MES
                        ,SUM(TRN_IMP) AS IMP_CAST
                        ,COUNT(CASE WHEN B.TRN_IMP>0 THEN 1 ELSE 0 END) AS CANT_CAST
                  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD` B
                      LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS C ON C.CTA_CVE=B.CTA_CVE
                            WHERE B.FCH_FCH BETWEEN (SELECT FCH_INI FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) AND (SELECT FCH_FIN FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`)
                                        AND B.TRN_CVE IN (502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517)
                                        GROUP BY 1,2,3
                                ) AS Q ON (Q.CTA_CVE=A.CTA_CVE AND Q.ANIO=A.ANIO_OBS AND Q.MES=A.MES_OBS) 
  LEFT JOIN (
                  SELECT B.CTA_CVE
                        ,CASE WHEN (C.CTA_ACT=0 OR C.CTA_ACT IS NULL) THEN B.CTA_CVE ELSE C.CTA_ACT END AS CTA_TRACK
                        ,EXTRACT(YEAR FROM FCH_FCH) AS ANIO 
                        ,EXTRACT(MONTH FROM FCH_FCH) AS MES
                        ,SUM(TRN_IMP) AS IMP_QUITA
                        ,COUNT(CASE WHEN B.TRN_IMP>0 THEN 1 ELSE 0 END) AS CANT_QUITA
                  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD` B
                      LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` AS C ON C.CTA_CVE=B.CTA_CVE
                            WHERE B.FCH_FCH BETWEEN (SELECT FCH_INI FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) AND (SELECT FCH_FIN FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`)
                                        AND B.TRN_CVE IN (307,407,763,764)
                                        GROUP BY 1,2,3,4
                                ) AS P ON (P.CTA_TRACK=A.CTA_CVE AND P.ANIO=A.ANIO_OBS AND P.MES=A.MES_OBS)


  LEFT JOIN (

        SELECT CTA_CVE, ANIO, MES, SUM (TRN_IMP) AS IMP_COM FROM `crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_NEGFIN_TM_COMISIONES` WHERE INDICADOR='COMISION_DISP' GROUP BY 1,2,3
  ) AS O ON A.CTA_CVE= O.CTA_CVE AND A.ANIO_OBS=O.ANIO AND A.MES_OBS=O.MES

  LEFT JOIN (
    SELECT *

    FROM(
         SELECT CTE_FCH_NAC,CTA_CVE, CTE_GEN,  CTE_ID, CTE_CVE_RFC, ROW_NUMBER() OVER(PARTITION BY CTA_CVE order by FCH_CARGA) ORDEN
         FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES`
           WHERE SYS_FTE = 12
    ) AS A

  LEFT JOIN (
        SELECT CTE_ID, CDP FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_DIREC_FTES`) AS B ON A.CTE_ID = B.CTE_ID
    WHERE ORDEN = 1

  ) AS N ON N.CTA_CVE=A.CTA_CVE 
  LEFT JOIN `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_1_TITULAR` AS B ON A.CTA_CVE=B.CTA_CVE
  LEFT JOIN `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_2_CTE_UNICO` AS C ON A.CTA_CVE=C.CTA_CVE;


-- ########################################################
-- #                                                      #
-- #                        DIM_FINAL                     #
-- #                                                      #
-- ######################################################## 
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_6_DISP_FIN`
AS
SELECT DISTINCT *,CURRENT_DATE('America/Mexico_City') AS FCH_CARGA 
FROM(
    SELECT A.*, ((ANIO_OBS - ANIO_ESTR)*12) + (MES_OBS-MES_ESTR) AS ANTIG_ESTR, 
                    CASE WHEN CTE_EDAD<30 THEN '30'			
            WHEN CTE_EDAD>=30 AND CTE_EDAD<35 THEN '30-35'
            WHEN CTE_EDAD>=35 AND CTE_EDAD<45 THEN '35-45'
            WHEN CTE_EDAD>=45 AND CTE_EDAD<50 THEN '45-50'
                WHEN CTE_EDAD>=50 THEN '50+' ELSE 'Sin clasificar' END AS RANGO_EDAD, 
                    
                CASE WHEN (TIP_INF IN (110,100) and TDA_ZNA ="1") THEN "01. Metro Sur"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="2") THEN "02. Metro Norte"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="3") THEN "03. Centro"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="4") THEN "04. Occidente"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="5") THEN "05. Golfo"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="6") THEN "06. Noreste"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="7") THEN "07. Bajio"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="8") THEN "08. Noroeste"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="9") THEN "09. Sureste"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA ="VAD") THEN "10. Vtas a Distancia"
                        WHEN (TIP_INF IN (110,100) and TDA_ZNA NOT IN ("OTRO", "VAD", '1','2','3','4','5','6','7','8','9')) THEN "11. OTRO"
                        WHEN TIP_INF IN (210,200,220) AND CTA_TDA_APE in ("0782", "0039") THEN "15.- ONLINE"
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Centro Norte' THEN '08.- Centro Norte'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Sur' THEN '12.- Sur'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Centro Sur' THEN '10.- Centro Sur'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Centro' THEN '04.- Metro Centro'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Golfo' THEN '11.- Golfo'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Occidente' THEN '06.- Occidente'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Oriente' THEN '02.- Metro Oriente'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Norte' THEN '03.- Metro Norte'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Norte' THEN '09.- Norte'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Metro Sur' THEN '01.- Metro Sur'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Bajio' THEN '05.- Bajio'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='Pacifico' THEN '07.- Pacificio'
                        WHEN (TIP_INF IN (210,200,220)) AND TDA_ZNA ='VDA' THEN '14.- VAD'
                ELSE '13.- OTRO'
                
                
                END CVE_ZNA,    
        

    FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_5_DISP_FLG` as a
);




--########################################################
--#                                                      #
--#           Funcion: CONTROL_CIFRAS                    #
--#                                                      #
--########################################################
INSERT INTO crp-pro-dwh-analiticagold.EIL_DP_MASTER.DIM_NEGFIN_TM_CONTROL_TEMPORALES(
        ESTRATEGIA,
        PASO,
        TABLA_CREADA,
        CIFRAS,
        FCH_CARGA,
        HRA_CARGA
    )
    VALUES
    (
        'PPL_NEGFIN_TM_DISPOSICIONES',
        '01 TMP_1_TITULAR',
        'DIM_NEGFIN_TMP_1_TITULAR',
        (SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_1_TITULAR),
        CURRENT_DATE('America/Mexico_City'),
        EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))

    ),
    (
        'PPL_NEGFIN_TM_DISPOSICIONES',
        '02 TMP_2_CTE_UNICO',
        'DIM_NEGFIN_TMP_2_CTE_UNICO',
        (SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_2_CTE_UNICO),
        CURRENT_DATE('America/Mexico_City'),
        EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))

    ),
    (
        'PPL_NEGFIN_TM_DISPOSICIONES',
        '02 TMP_3_DIMENSIONAL',
        'DIM_NEGFIN_TMP_3_DIM',
        (SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_3_DIM),
        CURRENT_DATE('America/Mexico_City'),
        EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))

    ),
    (
      'PPL_NEGFIN_TM_DISPOSICIONES',
      '03 TMP_3_DIMENSIONAL',
      'DIM_NEGFIN_TMP_3_DIM',
      (SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_3_DIM),
      CURRENT_DATE('America/Mexico_City'),
      EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))

   ),
   (
      'PPL_NEGFIN_TM_DISPOSICIONES',
      '04 TMP_4_DISP',
      'DIM_NEGFIN_TMP_4_DISP',
      (SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_4_DISP),
      CURRENT_DATE('America/Mexico_City'),
      EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))

   ),
   (
      'PPL_NEGFIN_TM_DISPOSICIONES',
      '05 TMP_5_DISP_FLG',
      'DIM_NEGFIN_TMP_5_DISP_FLG',
      (SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_5_DISP_FLG),
      CURRENT_DATE('America/Mexico_City'),
      EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))

   ),
   (
    'PPL_NEGFIN_TM_DISPOSICIONES',
    '06 TMP_6_DISP_FLG',
    'DIM_NEGFIN_TMP_6_DISP_FIN',
    (SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_6_DISP_FIN),
    CURRENT_DATE('America/Mexico_City'),
    EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))
  ),
  (
    'PPL_NEGFIN_TM_DISPOSICIONES',
    '07 TMP_6_DISP_FLG',
    'FAC_NEGFIN_TM_DISPOSICIONES_LT',
    (
      SELECT COUNT(*) FROM crp-pro-dwh-analiticagold.MUS_PRO_DWH_SAS_TEMP.FAC_NEGFIN_TM_DISPOSICIONES_LT_06 WHERE ANIOMES_OBS 
      BETWEEN (SELECT CAST(EXTRACT(YEAR FROM FCH_INI) * 100 + EXTRACT(MONTH FROM FCH_INI) AS INT64) 
                FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) 

      AND (SELECT CAST(EXTRACT(YEAR FROM FCH_FIN) * 100 + EXTRACT(MONTH FROM FCH_INI) AS INT64) 
            FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) ),

      CURRENT_DATE('America/Mexico_City'
    ),
    EXTRACT(TIME FROM  CURRENT_DATETIME('America/Mexico_City'))
  );


--#TRUE RPC HISTORICO // FALSE RPC MENSUAL
--Se activa reproceso mensual

SET FLG_RPC = FALSE; -- AQUÍ SE DESACTIVA EL MODO HISTORIA

--########################################################
--#                                                      #
--#           Funcion: Crea Temporal de tiempo           #
--#                                                      #
--########################################################
CREATE OR REPLACE TABLE `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`
AS 



SELECT * 
FROM (
    SELECT  
    CASE WHEN (EXTRACT(DAY FROM DATE('2026-07-01')) = 1 AND FLG_RPC = FALSE) THEN DATE_TRUNC(DATE_ADD(DATE('2026-07-01'), INTERVAL -1 DAY), MONTH)
         WHEN (EXTRACT(DAY FROM DATE('2026-07-01')) = 1 AND FLG_RPC = TRUE) THEN DATE('2017-01-01')
        ELSE DATE_TRUNC(DATE('2026-07-01'), MONTH)
        END AS FCH_INI,

    CASE WHEN EXTRACT(DAY FROM DATE('2026-07-01')) = 1 
        THEN LAST_DAY(DATE_ADD(DATE('2026-07-01'), INTERVAL -1 DAY), MONTH)
        ELSE LAST_DAY(DATE('2026-07-01'), MONTH)
        END AS FCH_FIN,

    
    'TM_DISPOSICIONES' AS ESTRATEGIA
);

--########################################################
--#                                                      #
--#           Funcion: MODULO BORRA_PARA_REPROCESO       #
--#                                                      #
--########################################################



DELETE FROM `crp-pro-dwh-analiticagold.MUS_PRO_DWH_SAS_TEMP.FAC_NEGFIN_TM_DISPOSICIONES_LT_06`
WHERE ANIOMES_OBS 
      
      BETWEEN (SELECT CAST(EXTRACT(YEAR FROM FCH_INI) * 100 + EXTRACT(MONTH FROM FCH_INI) AS INT64) 
               FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) 
      
      AND (SELECT CAST(EXTRACT(YEAR FROM FCH_FIN) * 100 + EXTRACT(MONTH FROM FCH_FIN) AS INT64) 
           FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`);

-- ########################################################
-- #                                                      #
-- #                        INSERTA_TABLA_DISP            #
-- #                                                      #
-- ########################################################

INSERT INTO `crp-pro-dwh-analiticagold.MUS_PRO_DWH_SAS_TEMP.FAC_NEGFIN_TM_DISPOSICIONES_LT_06`
SELECT *
FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_6_DISP_FIN`
WHERE ANIOMES_OBS 
      
      BETWEEN (SELECT CAST(EXTRACT(YEAR FROM FCH_INI) * 100 + EXTRACT(MONTH FROM FCH_INI) AS INT64) 
               FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`) 
      
      AND (SELECT CAST(EXTRACT(YEAR FROM FCH_FIN) * 100 + EXTRACT(MONTH FROM FCH_FIN) AS INT64) 
           FROM `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`);





--create table if not exists `crp-pro-dwh-analiticagold.MUS_PRO_DWH_SAS_TEMP.FAC_NEGFIN_TM_DISPOSICIONES_LT_06_2`
--clone `crp-pro-dwh-analiticagold.MUS_PRO_DWH_SAS_TEMP.FAC_NEGFIN_TM_DISPOSICIONES_LT_06`
--########################################################
--#                                                      #
--#           Funcion: BORRA_TEMPORALES_FIN              #
--#                                                      #
--########################################################
--DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_TIEMPO_DISP`;
--DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_1_TITULAR`;
--DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_2_CTE_UNICO`;
--DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_3_DIM`;
--DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_4_DISP`;
--DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_5_DISP_FLG`;
--DROP TABLE IF EXISTS `crp-pro-dwh-analiticagold.EIL_DP_RAW_TMP.DIM_NEGFIN_TMP_6_DISP_FIN`;

