INSERT INTO `crp-pro-cx-analitica.mus_pro_negfin_tablas_finales.FAC_NEGFIN_TM_SOBREGIROS`

WITH TIEMPO AS (
  -- Calcula automáticamente el año y mes del cierre anterior (Mes -1)
  SELECT 
    EXTRACT(YEAR FROM DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Mexico_City'), MONTH), INTERVAL 1 MONTH)) AS ANIO,
    EXTRACT(MONTH FROM DATE_SUB(DATE_TRUNC(CURRENT_DATE('America/Mexico_City'), MONTH), INTERVAL 1 MONTH)) AS MES
),

BASE_SOBREGIROS AS (
  SELECT
    CTA_CVE,
    ANIO_ESTR,
    MES_ESTR,
    SPID,
    LC_TRD,
    SDO_TRD,
    MONTO_TRD,
    IMP_SOBREGIRO,
    SECCION,
    TRN_APROB,
    TRN_RECH,
    TRN_TRD,
    TRN_APROB_AC,
    TOT_APRB,
    MONTO_AC,
    TOT_MONTO,
    CAST(FLG_SOB AS NUMERIC) AS FLG_SOB,
    FLG_EXCED,
    TIP_INF,
    SDO_CIERRE,
    CAST(COUNT(DISTINCT CTA_CVE) AS NUMERIC) AS CANT_CTAS,
    (ANIO_ESTR*100 + MES_ESTR) AS ANIOMES_ESTR
  FROM `crp-pro-cx-analitica.mus_pro_negfin_tablas_finales.DIM_NEGFIN_SOBREGIROS`
  GROUP BY 1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,22
),

SDO_CTA_Y AS (
 SELECT
    CASE WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL) THEN A.CTA_CVE ELSE C.CTA_ACT END AS CTA_CVE,
    A.ANIO,
    A.MES,
    A.TIP_INF,
    A.BR_SOLIC_CVE,
    A.CTA_EDO_CVE,
    A.CTA_TDA_APE,
    A.CTA_SDO_ACT,
    A.CCR_CVE_BLQ_UNO,
    A.CCR_CVE_BLQ_DOS,
    A.CTA_FACTOR_TASA,
    A.CTA_NVO_FACTOR_TASA,
    A.CTA_NIV_MOR,
    A.CTA_TOTALERO_FLG,
    A.CTA_IMP_LIM_CRD,
    A.CTA_MISC_CR_SCORE,
    A.CTA_FCH_BLQ_UNO,
    A.CTA_FCH_BLQ_DOS,
    (A.ANIO*100 + A.MES) AS ANIOMES_OBS,
    A.CTA_FCH_LIM_CRD,
    A.CTA_FCH_LAST_LIM,
    A.CTA_IMP_PAG_LTD,
    A.CTA_SDO_TOTALERO,
    A.CTA_SDO_ANT,
    A.CTA_IMP_ULT_PAGO,
    A.CTA_IMP_PAG_YTD, 
    A.BR_TIPO,
    A.CTA_STMT_FLG,        
    (
      SELECT MAX(CD)
      FROM UNNEST([
        SAFE_CAST(SUBSTR(A.CTA_HIST_PAGOS,1,1) AS NUMERIC),
        SAFE_CAST(SUBSTR(A.CTA_HIST_PAGOS,2,1) AS NUMERIC),
        SAFE_CAST(SUBSTR(A.CTA_HIST_PAGOS,3,1) AS NUMERIC),
        SAFE_CAST(SUBSTR(A.CTA_HIST_PAGOS,4,1) AS NUMERIC),
        SAFE_CAST(SUBSTR(A.CTA_HIST_PAGOS,5,1) AS NUMERIC),
        SAFE_CAST(SUBSTR(A.CTA_HIST_PAGOS,6,1) AS NUMERIC)
      ]) AS CD
    ) AS MAX_CD_6M,
    
    CASE WHEN A.CTA_IMP_LIM_CRD IS NULL OR A.CTA_IMP_LIM_CRD = 0 THEN -1
         ELSE SAFE_DIVIDE(A.CTA_SDO_ACT, A.CTA_IMP_LIM_CRD) END AS PCT_UTIL,
    A.LOG_CVE,
    C.CTA_ACT,
    CASE WHEN A.CTA_NIV_MOR >= 2 THEN 1 ELSE 0 END AS ENTRY,
       -- Rango límite crédito
    CASE
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 4000 THEN '1.-4,000'
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 7500 THEN '2.-4,000-7,499'
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 10000 THEN '3.-7,500-9,999'
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 15000 THEN '4.-10,000-14,999'
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 20000 THEN '5.-15,000-19,999'
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 30000 THEN '6.-20,000-29,999'
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD < 50000 THEN '7.-30,000-49,999'
      WHEN TIP_INF IN (100,110) AND CTA_IMP_LIM_CRD >= 50000 THEN '8.-50,000+'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 2000 THEN '1.-0-1,999'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 4000 THEN '2.-2,000-3,999'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 8000 THEN '3.-4,000-7,999'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 12000 THEN '4.-8,000-11,999'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 15000 THEN '5.-12,000 -14,999'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 18000 THEN '6.-15,000-17,999'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD < 20000 THEN '7.-18,000-19,999'
      WHEN TIP_INF IN (200,210) AND CTA_IMP_LIM_CRD >= 20000 THEN '8.->=20,000'
      ELSE 'OTRO'
    END AS RANG_LIM_CRD,
        -- Rango saldo actual
    CASE
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT < 4000 THEN '1.-4,000'
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT < 7500 THEN '2.-4,000-7,499'
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT < 10000 THEN '3.-7,500-9,999'
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT < 15000 THEN '4.-10,000-14,999'
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT < 20000 THEN '5.-15,000-19,999'
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT < 30000 THEN '6.-20,000-29,999'
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT < 50000 THEN '7.-30,000-49,999'
      WHEN TIP_INF IN (100,110) AND CTA_SDO_ACT >= 50000 THEN '8.-50,000+'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT < 2000 THEN '1.-0-1,999'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT < 4000 THEN '2.-2,000-3,999'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT < 8000 THEN '3.-4,000-7,999'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT < 12000 THEN '4.-8,000-11,999'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT < 15000 THEN '5.-12,000 -14,999'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT < 18000 THEN '6.-15,000-17,999'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT < 20000 THEN '7.-18,000-19,999'
      WHEN TIP_INF IN (200,210) AND CTA_SDO_ACT >= 20000 THEN '8.->=20,000'
      ELSE 'OTRO'
    END AS RANG_SDO_ACT,
    CASE
      WHEN CTA_NVO_FACTOR_TASA IN (66.00,64.00,64.50,65.50,68.00,85,84,84.5,85.5) THEN 'F.T5'
      WHEN CTA_NVO_FACTOR_TASA IN (61.20,62.20,62.70,63.70,66.20,80,80,80.5,81.5) THEN 'E.T4'
      WHEN CTA_NVO_FACTOR_TASA IN (53.11,54.86,55.36,56.36,58.86,77.42,77.6,78.1,79.1) THEN 'D.T3'
      WHEN CTA_NVO_FACTOR_TASA IN (42.04,45.54,46.04,47.04,49.54,69.83,69.83,70.33,71.33) THEN 'C.T2'
      WHEN CTA_NVO_FACTOR_TASA IN (31.39,32.39,32.89,33.89,36.39,60.36,60.36,60.86,61.86) THEN 'B.T1'
      WHEN CTA_NVO_FACTOR_TASA IN (14.99,15.49,16.49,18.99) THEN 'A.T0'
      WHEN CTA_NVO_FACTOR_TASA IN (26.56,27.43,27.68,28.18,29.43,38.71,38.8,39.05,39.55) THEN 'G.Empleados'
      ELSE 'H.Otros'
    END AS NIVEL_TASA,
    CASE 
            WHEN TRIM(A.CTA_STMT_FLG) = '0' THEN '0. DOMICILIO'
            WHEN TRIM(A.CTA_STMT_FLG) = '1' THEN '1. PAPERLESS'
            WHEN TRIM(A.CTA_STMT_FLG) = '2' THEN '2. EMAIL - DOMICILIO'
            WHEN TRIM(A.CTA_STMT_FLG) = '3' THEN '3. PAPERLESS + BANNER PAPERLESS'
            WHEN TRIM(A.CTA_STMT_FLG) = 'M' THEN '4. MORATORIO'
            WHEN TRIM(A.CTA_STMT_FLG) = 'R' THEN '5. REVISION'
            WHEN TRIM(A.CTA_STMT_FLG) IN ('O','H') THEN '6. ERRORES'
            ELSE 'Sin Clasificar' 
        END AS FLG_PAPERLESS,
    (CTA_IMP_LIM_CRD - CTA_SDO_ACT) AS OTB,
    A.CTA_FCH_PRM_CMP,
    A.CTA_FCH_ULT_PAG
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES` A
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` C
    ON A.CTA_CVE = C.CTA_CVE
 WHERE A.ANIO = (SELECT ANIO FROM TIEMPO) AND MES = (SELECT MES FROM TIEMPO)
  QUALIFY ROW_NUMBER() OVER(
    PARTITION BY 
      CASE WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL) THEN A.CTA_CVE ELSE C.CTA_ACT END,
      A.ANIO,
      A.MES
    ORDER BY 
      A.CTA_EDO_CVE ASC, 
      A.TIP_INF DESC,     
      A.LOG_CVE DESC     
  ) = 1
),

CTE_CLIE_FTES AS (
 SELECT
    CTE_FCH_NAC,
    CTA_CVE,
    CTE_GEN,
    CTE_NOM,
    CTE_APE_PAT,
    CTE_APE_MAT,
    CTE_CVE_RFC,
    CTE_CR_CVE,
    CTE_FCH_ALT,
    CTE_FCH_MODIF,
    CTE_ID,
    CTE_DIR_CVE,
    SOMS_ANT_CTE_CVE,
    CTE_CVE AS CLIE_CVE_ORIG,
    ROW_NUMBER() OVER (PARTITION BY CTA_CVE ORDER BY SOMS_ANT_CTE_CVE DESC) AS ORDEN
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CLIE_FTES`
  WHERE SYS_FTE = 12 
  QUALIFY ORDEN = 1
),

SEGMENTO_CTE AS (
  SELECT *
  FROM (
    SELECT
      CASE 
        WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL) 
          THEN A.CTA_CVE 
          ELSE C.CTA_ACT 
      END AS CTA_CVE,
      A.ANIO, 
      A.MES, 
      A.SEGMENTO_CLIENTE, 
      A.CTE_CVE_UNICO,
      A.NUM_PRODUCTOS,
      A.TIP_INF AS TIP_INF_SEG,
      ROW_NUMBER() OVER (
        PARTITION BY 
          CASE WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL)
            THEN A.CTA_CVE ELSE C.CTA_ACT END,
          A.ANIO,
          A.MES
        ORDER BY A.SEGMENTO_CLIENTE DESC
      ) AS rn
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_SEGMENTO_CTE` A
    LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` C 
      ON A.CTA_CVE = C.CTA_CVE
    WHERE A.ANIO = (SELECT ANIO FROM TIEMPO) AND A.MES = (SELECT MES FROM TIEMPO)
  )
  WHERE rn = 1   
),

AGREGADO_TARJETAS AS (
  SELECT CTA_CVE, SUM(CANT_ADIC) AS FLG_ADIC, SUM(CANT_TIT) AS FLG_TITU
  FROM (
      SELECT CTA_CVE, COUNT(DISTINCT(TRJ_NUM)) AS CANT_ADIC, 0 AS CANT_TIT
      FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ`
      WHERE IND_TIT IN('1', ' ')
        AND TRJ_EDO_CVE NOT IN('A ', 'B ', 'C ', 'E ','F', 'H ', 'J ', 'K ', 'O ', 'P ', 'Q ', 'S ', 'U ', 'X ', 'Y ', 'Z')
      GROUP BY 1
      UNION ALL 
      SELECT CTA_CVE, 0 AS CANT_ADIC, COUNT(DISTINCT(TRJ_NUM)) AS CANT_TIT
      FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRJ`
      WHERE IND_TIT = '0'
        AND TRJ_EDO_CVE NOT IN('A ', 'B ', 'C ', 'E ','F', 'H ', 'J ', 'K ', 'O ', 'P ', 'Q ', 'S ', 'U ', 'X ', 'Y ', 'Z')
      GROUP BY 1
  )
  GROUP BY 1
),

POLIZAS_PIF AS (
  SELECT DISTINCT SAFE_CAST(POLIZAEXTERNA AS NUMERIC) AS CTA_CVE
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_POLIZAS`
  WHERE LINEADENEGOCIO = 'Polizas Internas'
    AND ESTADO IN('Activado','Activado por migracion','Reactivado')
),

SEGMENTO_RFM AS (
  SELECT
    CASE 
      WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL) THEN A.CTA_CVE 
      ELSE C.CTA_ACT END AS CTA_CVE,
    A.ANIO, A.MES, A.RFM_CREDITO AS SEGMENTO_RFM
  FROM `crp-pro-cx-semantica.mus_pro_shared_views.VDIM_SGMTOS_RFM_HIST_AANF` A
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` C ON A.CTA_CVE = C.CTA_CVE
   WHERE A.ANIO = (SELECT ANIO FROM TIEMPO) AND A.MES = (SELECT MES FROM TIEMPO)
),

INTERES_MSI_AGG AS (
  SELECT
    CASE 
    WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL) THEN A.CTA_CVE 
    ELSE C.CTA_ACT END AS CTA_CVE,
    A.TIP_INF, A.ANIO, A.MES,
    SUM(CASE WHEN A.INDICADOR = 'INTERESES_FIN' THEN A.IMP ELSE 0 END) AS IMP_INT_FIN,
    SUM(CASE WHEN A.INDICADOR = 'INTERESES_MOR' THEN A.IMP ELSE 0 END) AS IMP_INT_MOR,
    SUM(CASE WHEN A.INDICADOR LIKE 'MSI%' THEN A.IMP ELSE 0 END) AS IMP_INT_MSI
  FROM `crp-pro-cx-semantica.mus_pro_negfin_shared_views.VFAC_NEGFIN_INTER_MSI` A
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` C ON A.CTA_CVE = C.CTA_CVE
   WHERE A.ANIO = (SELECT ANIO FROM TIEMPO) AND A.MES = (SELECT MES FROM TIEMPO)
  GROUP BY 1,2,3,4
),

CTE_MICREDITO AS (
  SELECT DISTINCT SAFE_CAST(CARD_NUMBER AS NUMERIC) AS CTA_CVE
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_CTE_MICREDITO`
  WHERE ANIO = (SELECT ANIO FROM TIEMPO) AND MES = (SELECT MES FROM TIEMPO)
),

AGG_CAST AS (
  SELECT
    CASE WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL) THEN B.CTA_CVE ELSE C.CTA_ACT END AS CTA_CVE,
    EXTRACT(YEAR FROM B.FCH_FCH) AS ANIO,
    EXTRACT(MONTH FROM B.FCH_FCH) AS MES,
    SUM(B.TRN_IMP) AS IMP_CAST,
    CAST(COUNT(CASE WHEN B.TRN_IMP > 0 THEN 1 END) AS NUMERIC) AS CANT_CAST,
    MAX(B.FCH_FCH) AS CTA_FCH_CASTIGO
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD` B
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` C ON B.CTA_CVE = C.CTA_CVE
  WHERE 
    B.TRN_CVE IN (502,503,504,505,506,507,508,509,510,511,512,513,514,515,516,517)
    AND EXTRACT(YEAR FROM B.FCH_FCH) = (SELECT ANIO FROM TIEMPO) AND EXTRACT(MONTH FROM B.FCH_FCH) = (SELECT MES FROM TIEMPO)
  GROUP BY 1,2,3
),

AGG_QUITA AS (
  SELECT
    CASE WHEN (C.CTA_ACT = 0 OR C.CTA_ACT IS NULL) THEN B.CTA_CVE ELSE C.CTA_ACT END AS CTA_TRACK,
    EXTRACT(YEAR FROM B.FCH_FCH) AS ANIO,
    EXTRACT(MONTH FROM B.FCH_FCH) AS MES,
    SUM(B.TRN_IMP) AS IMP_QUITA,
    COUNT(CASE WHEN B.TRN_IMP > 0 THEN 1 END) AS CANT_QUITA
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD` B
  LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA_TRACK` C ON B.CTA_CVE = C.CTA_CVE
  WHERE 
    B.TRN_CVE IN (307,407,763,764) AND EXTRACT(YEAR FROM B.FCH_FCH) = (SELECT ANIO FROM TIEMPO) AND EXTRACT(MONTH FROM B.FCH_FCH) = (SELECT MES FROM TIEMPO)
  GROUP BY 1,2,3
),

MACROSEG_V1 AS (
  WITH BASE_V1 AS (
    SELECT
      CTA_CVE,
      FEC_MACROSEG,
      SAFE_CAST(SEGMENTO_OFICIAL AS STRING) AS SEGMENTO_OFICIAL
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_MACROSEGMENTO`
    WHERE FEC_MACROSEG BETWEEN '2019-01-01' AND '2022-12-31'
  )
  SELECT
    CTA_CVE,
    FEC_MACROSEG AS FCH_MAX,
    SEGMENTO_OFICIAL
  FROM (
    SELECT
      CTA_CVE,
      FEC_MACROSEG,
      SEGMENTO_OFICIAL,
      ROW_NUMBER() OVER (
        PARTITION BY CTA_CVE,
                     EXTRACT(YEAR FROM FEC_MACROSEG),
                     EXTRACT(MONTH FROM FEC_MACROSEG)
        ORDER BY FEC_MACROSEG DESC
      ) AS RN
    FROM BASE_V1
  )
  WHERE RN = 1
),

MACROSEG_V2 AS (
  WITH BASE_V2 AS (
    SELECT
      CTA_CVE,
      FEC_MACROSEG,
      SAFE_CAST(SEGMENTO_OFICIAL AS STRING) AS SEGMENTO_OFICIAL
    FROM `crp-pro-cx-analitica.mus_pro_negfin_tablas_finales.FAC_NEGFIN_MACROSEGMENTO_V2`
    WHERE FEC_MACROSEG >= '2023-01-01'
  )
  SELECT
    CTA_CVE,
    FEC_MACROSEG AS FCH_MAX,
    SEGMENTO_OFICIAL
  FROM (
    SELECT
      CTA_CVE,
      FEC_MACROSEG,
      SEGMENTO_OFICIAL,
      ROW_NUMBER() OVER (
        PARTITION BY CTA_CVE,
                     EXTRACT(YEAR FROM FEC_MACROSEG),
                     EXTRACT(MONTH FROM FEC_MACROSEG)
        ORDER BY FEC_MACROSEG DESC
      ) AS RN
    FROM BASE_V2
  )
  WHERE RN = 1
),

MACROSEG AS (
  SELECT CTA_CVE, FCH_MAX, SEGMENTO_OFICIAL FROM MACROSEG_V1
  UNION ALL
  SELECT CTA_CVE, FCH_MAX, SEGMENTO_OFICIAL FROM MACROSEG_V2
),

VDIM_TDA AS (
  SELECT
    TDA_CVE,
    TDA_ZNA,
    TDA_EDO_CVE
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_TDA`
),

ING_INF AS (
  SELECT 
  CTA_TRACK,
  PTI_TOT,
  EXTRACT(YEAR FROM FECHA_SEGUIMIENTO) AS ANIO,
  EXTRACT(MONTH FROM FECHA_SEGUIMIENTO) AS MES
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_ING_INFERIDO`
  WHERE EXTRACT(YEAR FROM FECHA_SEGUIMIENTO) >= 2019
),

CVE_ZONA_SBB AS (
  SELECT TDA_CVE
        ,TDA_DES
        ,CASE 
              WHEN ZONA_DES IS NULL THEN "Otro"
              WHEN TRIM(ZONA_DES) = '' THEN "Otro" 
              WHEN ZONA_DES IN ('NULL', 'null', 'Sin Identificar') THEN "Otro"
              WHEN ZONA_DES = "Pacífico" THEN "Pacifico"
              WHEN ZONA_DES = "Cierre" THEN "Otro"
              WHEN ZONA_DES = "Omnicanal" THEN "Canal Digital"
              WHEN ZONA_DES = "Bajío" THEN "Bajio"
              ELSE COALESCE(ZONA_DES, "Otro")
           END ZONA
        ,CASE 
          WHEN ZONA_DES IS NULL THEN '13'
          WHEN ZONA_DES ="Metro Sur" THEN '1'
          WHEN ZONA_DES ="Metro Oriente" then '2'
          WHEN ZONA_DES ="Metro Norte" then '3'
          WHEN ZONA_DES ="Metro Centro" then '4'
          WHEN ZONA_DES ="Bajio" then '5'
          WHEN ZONA_DES ="Occidente" then '6'
          WHEN ZONA_DES ="Pacifico" then '7'
          WHEN ZONA_DES ="Centro Norte" then '8'
          WHEN ZONA_DES ="Norte" then '9'
          WHEN ZONA_DES ="Centro Sur" then '10'
          WHEN ZONA_DES ="Golfo" then '11'
          WHEN ZONA_DES ="Sur" then '12'
          ELSE '13' END AS ID_ZONA
  FROM (SELECT *
              ,ROW_NUMBER() OVER (PARTITION BY TDA_CVE ORDER BY ANIO DESC, MES DESC) as rn
        FROM crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VDIM_NEGFIN_ZONAS_SBB)
  WHERE RN = 1
),

WEB AS(
  SELECT *
  FROM (SELECT DISTINCT 
                A.CTA_CVE 
                , A.TIP_INF 
                ,WEB
                ,EXTRACT ( YEAR FROM A.FCH_FCH) AS ANIO 
                ,EXTRACT ( MONTH FROM A.FCH_FCH) AS mes 
         FROM (SELECT CTA_CVE ,TIP_INF,FCH_FCH,TRN_TDA_CVE,
                CASE WHEN TRN_TDA_CVE IN ("0039") THEN 1 ELSE 0 END AS WEB 
                FROM crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD
                WHERE TRN_CVE IN (1,101)
                and SEC_CVE != '0936'
                AND FCH_FCH >= '2017-01-01') as A
        ) 
  WHERE WEB=1
)

SELECT
  -- PP / TM
  Z.CTA_CVE,
  Z.ANIO_ESTR,
  Z.MES_ESTR,
  Z.TIP_INF,
  Z.SPID,
  Z.LC_TRD,
  Z.SDO_TRD,
  Z.MONTO_TRD,
  Z.IMP_SOBREGIRO,
  Z.SECCION,
  Z.TRN_APROB,
  Z.TRN_RECH,
  Z.TRN_TRD,
  Z.TRN_APROB_AC,
  Z.TOT_APRB,
  Z.MONTO_AC,
  Z.TOT_MONTO,
  Z.FLG_SOB,
  Z.FLG_EXCED,
  Z.SDO_CIERRE,
  CAST(NULL AS NUMERIC) AS CTA_ACT,
  CAST(NULL AS NUMERIC) AS CTA_ORG,
  CAST(Z.ANIOMES_ESTR AS NUMERIC) AS ANIOMES_ESTR,
  -- SDO_CTA_MES / observación
  CAST(C.ANIO AS NUMERIC) AS ANIO_OBS,
  C.MES AS MES_OBS,
  C.CTA_EDO_CVE,
  C.LOG_CVE,
  C.BR_SOLIC_CVE,
  C.CTA_TDA_APE,
  C.CTA_SDO_ACT,
  C.CCR_CVE_BLQ_UNO,
  C.CCR_CVE_BLQ_DOS,
  C.CTA_FACTOR_TASA,
  C.CTA_NVO_FACTOR_TASA AS CTA_TASA_RBP,
  C.CTA_NIV_MOR,
  C.ENTRY,
  C.CTA_TOTALERO_FLG,
  C.CTA_IMP_LIM_CRD,
  C.CTA_MISC_CR_SCORE,
  C.CTA_FCH_PRM_CMP,
  C.CTA_FCH_ULT_PAG,
  C.CTA_FCH_LIM_CRD,
  C.CTA_IMP_PAG_LTD,
  C.CTA_FCH_LAST_LIM,
  C.CTA_SDO_TOTALERO,
  C.CTA_SDO_ANT,
  C.CTA_FCH_BLQ_UNO,
  C.CTA_FCH_BLQ_DOS,
  C.CTA_IMP_ULT_PAGO,
  CASE WHEN R.CTA_CVE IS NULL THEN '0' ELSE '1' END AS FLG_DIG,
  C.FLG_PAPERLESS,
  
  -- Variables de Madurez y Antigüedad
  SAFE_CAST(((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA)))AS NUMERIC) AS MOBS_ALT_ESTR,
  SAFE_CAST(((C.ANIO - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (C.MES - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) AS NUMERIC) AS MOBS_ALT,
  CASE 
     WHEN ((C.ANIO - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (C.MES - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 6 THEN 'A.0M-6M'
     WHEN ((C.ANIO - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (C.MES - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 12 THEN 'B.7M-12M'
     WHEN ((C.ANIO - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (C.MES - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 24 THEN 'C.13M-24M'
     WHEN ((C.ANIO - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (C.MES - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 36 THEN 'D.25M-36M'
     WHEN ((C.ANIO - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (C.MES - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 48 THEN 'E.37M-48M'
     WHEN ((C.ANIO - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (C.MES - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 60 THEN 'F.49M-60M'
     ELSE 'G.61M+' 
  END AS RANG_MOBS,
  CASE WHEN CTA_SDO_ACT > 0 THEN '0' ELSE '1' END AS CTAS_CON_SDO,
  Z.CANT_CTAS,
  
  -- Variables de Delincuencia (CD2)
  CASE WHEN C.CTA_NIV_MOR = 2 THEN 1 ELSE 0 END AS CD2,
  CASE WHEN C.CTA_NIV_MOR >= 2 THEN 1 ELSE 0 END AS CD2_MAS,
  CASE WHEN C.CTA_NIV_MOR = 2 THEN (((C.ANIO - Z.ANIO_ESTR) * 12) + (C.MES - Z.MES_ESTR)) ELSE 0 END AS MOB_CD2,

  -- Segmentación por Árboles de Riesgo
  CASE WHEN Z.TIP_INF = 100 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) BETWEEN 0 AND 11 THEN '1.DE 0 A 11'
       WHEN Z.TIP_INF = 100 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) BETWEEN 12 AND 48 THEN '2.DE 12 A 47'
       WHEN Z.TIP_INF = 100 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) >= 48 THEN '3.MAYOR O IGUAL A 48'
       WHEN Z.TIP_INF = 110 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) BETWEEN 0 AND 11 THEN '1.DE 0 A 11'
       WHEN Z.TIP_INF = 110 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) BETWEEN 12 AND 59 THEN '2.DE 12 A 59'
       WHEN Z.TIP_INF = 110 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) BETWEEN 60 AND 119 THEN '3.DE 60 A 119'
       WHEN Z.TIP_INF = 110 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) >= 120 THEN '4.MAYOR O IGUAL A 120'
  END AS NIVEL_2,

  CASE WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE BETWEEN 0 AND 379 THEN '1.MENOR O IGUAL A 379'
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE <= 399 THEN '2.DE 380 A 399'
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE <= 419 THEN '3.DE 400 A 419'
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE <= 449 THEN '4.DE 420 A 449'
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE >= 450 THEN '5.MAYOR O IGUAL A 450'
       WHEN Z.TIP_INF = 110 AND C.CTA_MISC_CR_SCORE BETWEEN 0 AND 799 THEN '1.MENOR O IGUAL A 799'
       WHEN Z.TIP_INF = 110 AND C.CTA_MISC_CR_SCORE <= 849 THEN '2.DE 800 A 849'
       WHEN Z.TIP_INF = 110 AND C.CTA_MISC_CR_SCORE <= 884 THEN '3.DE 850 A 884'
       WHEN Z.TIP_INF = 110 AND C.CTA_MISC_CR_SCORE <= 899 THEN '4.DE 885 A 899'
       WHEN Z.TIP_INF = 110 AND C.CTA_MISC_CR_SCORE <= 919 THEN '5.DE 900 A 919'
       WHEN Z.TIP_INF = 110 AND C.CTA_MISC_CR_SCORE <= 934 THEN '6.DE 920 A 934'
       WHEN Z.TIP_INF = 110 AND C.CTA_MISC_CR_SCORE >= 935 THEN '7.MAYOR O IGUAL A 935'
  END AS NIVEL_3,

  CASE WHEN Z.TIP_INF = 100 AND ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) BETWEEN 0 AND 11 THEN 1
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE <= 399 THEN 2
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE <= 419 THEN 3
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE <= 449 THEN 4
       WHEN Z.TIP_INF = 100 AND C.CTA_MISC_CR_SCORE >= 450 THEN 5
       ELSE 6 END AS ID_NODO, 

  '1. TOTAL' AS ID_TOTAL,
  '2. 2 AL 5' AS ID_NODO_ANTIGUEDAD,

  -- Variables de Tarjetas, Transacciones y Origen
  CAST(COALESCE(TRJ.FLG_ADIC, 0) AS NUMERIC) AS FLG_ADIC,
  CAST(COALESCE(TRJ.FLG_TITU, 0)AS NUMERIC) AS FLG_TITU,
  CAST(C.BR_TIPO AS NUMERIC) AS BR_TIPO,
  C.CTA_IMP_PAG_YTD,
  CASE WHEN Z.ANIO_ESTR < 2009 OR Z.ANIO_ESTR IS NULL THEN '<2009'
       ELSE CONCAT(Z.ANIO_ESTR, RIGHT(CONCAT("0", Z.MES_ESTR), 2)) 
  END AS COSECHA,
  CAST(SSEG.ANIO AS NUMERIC) AS ANIO_SEG,
  CAST(SSEG.MES AS NUMERIC) AS MES_SEG,
  SSEG.TIP_INF_SEG,
  CASE WHEN POL.CTA_CVE IS NULL THEN 0 ELSE 1 END AS PIF,
  CAST(CF.CLIE_CVE_ORIG AS NUMERIC) AS CTE_CVE,
  
  -- Cálculos / Riesgo Originales
  CASE WHEN Z.TIP_INF IN (100,110,200, 210) AND CTA_MISC_CR_SCORE<=0 THEN '0.NO CALIFICADO'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=405 AND ((ANIO_ESTR*100)+MES_ESTR)<=202201 THEN '1.VERY HIGH'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=426 AND ((ANIO_ESTR*100)+MES_ESTR)<=202201 THEN '2.HIGH'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=450 AND ((ANIO_ESTR*100)+MES_ESTR)<=202201 THEN '3.MEDIUM'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=467 AND ((ANIO_ESTR*100)+MES_ESTR)<=202201 THEN '4.LOW'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE>=468 AND ((ANIO_ESTR*100)+MES_ESTR)<=202201 THEN '5.VERY LOW'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=856 AND ((ANIO_ESTR*100)+MES_ESTR)<=202203 THEN '1.VERY HIGH'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=894 AND ((ANIO_ESTR*100)+MES_ESTR)<=202203 THEN '2.HIGH'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=929 AND ((ANIO_ESTR*100)+MES_ESTR)<=202203 THEN '3.MEDIUM'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=952 AND ((ANIO_ESTR*100)+MES_ESTR)<=202203 THEN '4.LOW'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE>=953 AND ((ANIO_ESTR*100)+MES_ESTR)<=202203 THEN '5.VERY LOW' 
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=455 AND ((ANIO_ESTR*100)+MES_ESTR)>=202202 AND ((ANIO_ESTR*100)+MES_ESTR)<202602 THEN '1.VERY HIGH'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=525 AND ((C.ANIO*100)+C.MES)>=202202 AND ((ANIO_ESTR*100)+MES_ESTR)<202602 THEN '2.HIGH'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=603 AND ((C.ANIO*100)+C.MES)>=202202 AND ((ANIO_ESTR*100)+MES_ESTR)<202602 THEN '3.MEDIUM'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<=661 AND ((C.ANIO*100)+C.MES)>=202202 AND ((ANIO_ESTR*100)+MES_ESTR)<202602 THEN '4.LOW'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE>661 AND ((C.ANIO*100)+C.MES)>=202202 AND ((ANIO_ESTR*100)+MES_ESTR)<202602 THEN '5.VERY LOW'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=455 AND ((ANIO_ESTR*100)+MES_ESTR)>=202204 THEN '1.VERY HIGH'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=525 AND ((ANIO_ESTR*100)+MES_ESTR)>=202204 THEN '2.HIGH'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=603 AND ((ANIO_ESTR*100)+MES_ESTR)>=202204 THEN '3.MEDIUM'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE<=661 AND ((ANIO_ESTR*100)+MES_ESTR)>=202204 THEN '4.LOW'
       WHEN Z.TIP_INF=110 AND CTA_MISC_CR_SCORE>661 AND ((ANIO_ESTR*100)+MES_ESTR)>=202204 THEN '5.VERY LOW' 
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<438 AND ((ANIO_ESTR*100)+MES_ESTR)>=202602 THEN '1.VERY HIGH'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<519 AND ((ANIO_ESTR*100)+MES_ESTR)>=202602 THEN '2.HIGH'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<567 AND ((ANIO_ESTR*100)+MES_ESTR)>=202602 THEN '3.MEDIUM'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE<654 AND ((ANIO_ESTR*100)+MES_ESTR)>=202602 THEN '4.LOW'
       WHEN Z.TIP_INF=100 AND CTA_MISC_CR_SCORE>=654 AND ((ANIO_ESTR*100)+MES_ESTR)>=202602 THEN '5.VERY LOW'
       WHEN Z.TIP_INF = 210 AND ((ANIO_ESTR = 2023 AND MES_ESTR <= 8) OR ANIO_ESTR <= 2022) THEN              			
          CASE                			
            WHEN CTA_MISC_CR_SCORE = 0 OR CTA_MISC_CR_SCORE IS NULL THEN '0.NO CALIFICADO'
            WHEN CTA_MISC_CR_SCORE < 452 THEN '5.VERY HIGH'             			
            WHEN CTA_MISC_CR_SCORE < 532 THEN '4.HIGH'                  			
            WHEN CTA_MISC_CR_SCORE < 638 THEN '3.MEDIUM'                			
            WHEN CTA_MISC_CR_SCORE < 715 THEN '2.LOW'             			
            WHEN CTA_MISC_CR_SCORE >= 715 THEN '1.VERY LOW'             			
            ELSE ''                 			
          END                 			              			
       WHEN Z.TIP_INF = 210 AND ((ANIO_ESTR = 2023 AND MES_ESTR >= 9) OR (ANIO_ESTR >= 2024)) THEN              			
          CASE                			
            WHEN CTA_MISC_CR_SCORE = 0 OR CTA_MISC_CR_SCORE IS NULL THEN '0.NO CALIFICADO'
            WHEN CTA_MISC_CR_SCORE <= 455 THEN '5.VERY HIGH'                  			
            WHEN CTA_MISC_CR_SCORE <= 525 THEN '4.HIGH'                 			
            WHEN CTA_MISC_CR_SCORE <= 603 THEN '3.MEDIUM'               			
            WHEN CTA_MISC_CR_SCORE <= 661 THEN '2.LOW'                  			
            WHEN CTA_MISC_CR_SCORE >= 662 THEN '1.VERY LOW'             			
            ELSE ''                 			
          END                 			           			
       WHEN Z.TIP_INF = 200 THEN          			
          CASE                			
            WHEN CTA_MISC_CR_SCORE = 0 OR CTA_MISC_CR_SCORE IS NULL THEN '0.NO CALIFICADO'                 			
            WHEN CTA_MISC_CR_SCORE < 452 THEN '5.VERY HIGH'             			
            WHEN CTA_MISC_CR_SCORE < 532 THEN '4.HIGH'                  			
            WHEN CTA_MISC_CR_SCORE < 638 THEN '3.MEDIUM'                			
            WHEN CTA_MISC_CR_SCORE < 715 THEN '2.LOW'             			
            WHEN CTA_MISC_CR_SCORE >= 715 THEN '1.VERY LOW'             			
            ELSE ''                 			
          END                 			
       ELSE '0.NO CALIFICADO' 
  END AS NIV_RIESGO,
  C.OTB,
  CASE 
    WHEN C.CTA_IMP_LIM_CRD <= 0 THEN -1 
    ELSE SAFE_DIVIDE(C.CTA_SDO_ACT, C.CTA_IMP_LIM_CRD)
  END AS PRCT_UTI,
  C.ANIOMES_OBS AS ANIOMES_OBS,
  CASE WHEN C.CTA_NIV_MOR IN (0,1) THEN '0.-CTAS_VIG'
       WHEN C.CTA_NIV_MOR = 2 THEN '1.-1-29 DIAS'
       WHEN C.CTA_NIV_MOR = 3 THEN '2.-30_DIAS'
       WHEN C.CTA_NIV_MOR = 4 THEN '3.-60_DIAS'
       WHEN C.CTA_NIV_MOR = 5 THEN '4.-90_DIAS'
       WHEN C.CTA_NIV_MOR = 6 THEN '5.-120_DIAS'
       WHEN C.CTA_NIV_MOR = 7 THEN '6.-150_DIAS'
       WHEN C.CTA_NIV_MOR = 8 THEN '7.-180_DIAS'
       ELSE '8.-210_DIAS' 
  END AS RANG_NIV_MOR,
  CASE
      WHEN C.PCT_UTIL <= .20 THEN 'A.1-20'
      WHEN C.PCT_UTIL <= .25 THEN 'B.21-25'
      WHEN C.PCT_UTIL <= .30 THEN 'C.26-30'
      WHEN C.PCT_UTIL <= .35 THEN 'D.31-35'
      WHEN C.PCT_UTIL <= .40 THEN 'E.36-40'
      WHEN C.PCT_UTIL <= .45 THEN 'F.41-45'
      WHEN C.PCT_UTIL <= .50 THEN 'G.46-50'
      WHEN C.PCT_UTIL <= .75 THEN 'H.51-75'
      WHEN C.PCT_UTIL <= .85 THEN 'I.76-85'
      ELSE 'J.86+'
  END AS RANG_UTILIZA,
  C.RANG_SDO_ACT,
  C.RANG_LIM_CRD,
  CTA_INFO.CTA_FCH_ALTA,
  TD.TDA_EDO_CVE,
  CASE
    WHEN Z.TIP_INF IN (210,200,220) AND C.CTA_TDA_APE IN ('0782','0039') THEN 'Canal Digital'
    WHEN Z.TIP_INF IN (210,200,220) AND C.CTA_TDA_APE IN('0687','0024','0329','0778') THEN 'Otro'
    WHEN Z.TIP_INF IN (210,200,220) THEN SBB.ZONA
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA NOT IN ('OTRO','VAD','1','2','3','4','5','6','7','8','9')) THEN 'Otro'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = 'VAD') THEN 'Canal Digital'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '1') THEN '1. Metro Sur'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '2') THEN '2. Metro Norte'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '3') THEN '3. Centro'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '4') THEN '4. Occidente'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '5') THEN '5. Golfo'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '6') THEN '6. Noreste'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '7') THEN '7. Bajio'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '8') THEN '8. Noroeste'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '9') THEN '9. Sureste'
    ELSE 'Otro'
  END AS CVE_ZNA,
  SSEG.CTE_CVE_UNICO,
  SSEG.SEGMENTO_CLIENTE,
  SSEG.NUM_PRODUCTOS,
  SAFE_CAST(DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC), YEAR)AS NUMERIC) AS EDAD,
  CASE WHEN CF.CTE_GEN = 1 THEN 'MASCULINO'
       WHEN CF.CTE_GEN = 2 THEN 'FEMENINO'
       ELSE 'SIN GENERO' END AS GENERO,
  CF.CTE_NOM,
  CF.CTE_APE_PAT,
  CF.CTE_APE_MAT,
  CF.CTE_CVE_RFC,
  CF.CTE_CR_CVE,
  CF.CTE_FCH_NAC,
  CF.CTE_FCH_ALT,
  CF.CTE_FCH_MODIF,
  CF.CTE_ID,
  CF.CTE_DIR_CVE,
  CF.SOMS_ANT_CTE_CVE,
  ING.PTI_TOT AS PTI,
  RFM.SEGMENTO_RFM,
  SAFE_CAST((((C.ANIO - Z.ANIO_ESTR) * 12) + (C.MES - Z.MES_ESTR))AS NUMERIC)AS ANTIG_ESTR,
  SAFE_CAST(M.SEGMENTO_OFICIAL AS NUMERIC) AS MACROSEGMENTO,
  CASE 
    WHEN DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) <21 THEN "<21"
    WHEN DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) >=21 AND DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) <=24 THEN "21-24"
    WHEN DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) >=25 AND DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) <=29 THEN "25-29"
    WHEN DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR)>29 AND DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) <=37 THEN "30-37"
    WHEN DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) >37 AND DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) <=44 THEN "38-44"
    WHEN DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) >44 AND DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) <=59 THEN "45-59"
    WHEN DATE_DIFF(PARSE_DATE('%Y%m%d', CAST(Z.ANIOMES_ESTR AS STRING) || '01'), DATE(CTE_FCH_NAC),YEAR) >=60 THEN "60 +" END AS RANG_EDAD,  
  CASE
    WHEN ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 6 THEN '1. 0-6 Meses'
    WHEN ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 12 THEN '2. 7-12 Meses'
    WHEN ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 24 THEN '3. 13-24 Meses'
    WHEN ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 36 THEN '4. 25-36 Meses'
    WHEN ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 48 THEN '5. 37-48 Meses'
    WHEN ((Z.ANIO_ESTR - EXTRACT(YEAR FROM CTA_INFO.CTA_FCH_ALTA)) * 12 + (Z.MES_ESTR - EXTRACT(MONTH FROM CTA_INFO.CTA_FCH_ALTA))) <= 60 THEN '6. 49-60 Meses'
    ELSE '7. 61+ Meses' END AS MOB,
  COALESCE(IMP.IMP_INT_MOR, 0) AS IMP_INT_MOR,
  COALESCE(IMP.IMP_INT_FIN, 0) AS IMP_INT_FIN,
  COALESCE(IMP.IMP_INT_MOR,0) + COALESCE(IMP.IMP_INT_FIN,0) AS IMP_INT_TOT,
  COALESCE(IMP.IMP_INT_MSI, 0) AS IMP_INT_MSI,
  CASE WHEN C.CTA_NIV_MOR IN (3,4,5,6,7,8,9) THEN '1' ELSE '0' END AS FLG_30,
  CASE WHEN C.CTA_NIV_MOR IN (5,6,7,8,9) THEN '1' ELSE '0' END AS FLG_90,
  COALESCE(Q.IMP_CAST, 0) AS IMP_CAST2,
  COALESCE(Q.CANT_CAST, 0) AS CANT_CAST, 
  COALESCE(Q.IMP_CAST, 0) AS IMP_CAST,
  COALESCE(P.IMP_QUITA, 0) AS IMP_QUITA,
  COALESCE(P.CANT_QUITA, 0) AS CANT_QUITA,
  Q.CTA_FCH_CASTIGO AS CTA_FCH_CASTIGO,
  CASE WHEN ((Q.ANIO - Z.ANIO_ESTR) * 12 + (Q.MES - Z.MES_ESTR)) <= 12 THEN 'Y1'
       WHEN ((Q.ANIO - Z.ANIO_ESTR) * 12 + (Q.MES - Z.MES_ESTR)) <= 24 THEN 'Y2'
       WHEN ((Q.ANIO - Z.ANIO_ESTR) * 12 + (Q.MES - Z.MES_ESTR)) <= 36 THEN 'Y3'
       ELSE 'OTRO' END AS YTD_CAST,
  CASE WHEN ((C.ANIO - Z.ANIO_ESTR) * 12 + (C.MES - Z.MES_ESTR)) <= 12 THEN 'Y1'
       WHEN ((C.ANIO - Z.ANIO_ESTR) * 12 + (C.MES - Z.MES_ESTR)) <= 24 THEN 'Y2'
       WHEN ((C.ANIO - Z.ANIO_ESTR) * 12 + (C.MES - Z.MES_ESTR)) <= 36 THEN 'Y3'
       ELSE 'OTRO' END AS YTD,
  CASE     
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (36.39,33.89,32.89,32.39,31.39,29.49,27.99,25.99) then 'T1'
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (49.54,47.04,46.04,45.54,42.04,39.49,37.99,33.99) then 'T2'
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (58.86,56.36,55.36,54.86,53.11,55,49.89,48.39,44.39) then 'T3'
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (66.20,63.70,62.70,62.20,61.2,57.49,55.99,51.99) then 'T4'
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (68,65.5,64.5,64,66,65.49,63.99,59.99) then 'T5'
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (29.43,28.18,27.68,27.43,26.55,24.95,24.20,22.20) then 'TASA EMPL'
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (14.99,15.49,16.49,18.99) then 'T0'
    when C.TIP_INF IN (100,110) AND CTA_NVO_FACTOR_TASA IN (0) then 'TASA CORPORATIVO'
    when C.TIP_INF IN (200,210) AND CTA_NVO_FACTOR_TASA IN (48.99,56.70,60.36,60.36,60.86,61.86) then 'T1'
    when C.TIP_INF IN (200,210) AND CTA_NVO_FACTOR_TASA IN (55.99,65.60,69.83,69.83,70.33,71.33) then 'T2'
    when C.TIP_INF IN (200,210) AND CTA_NVO_FACTOR_TASA IN (63.99,75.00,77.42,77.60,78.10,79.10) then 'T3'
    when C.TIP_INF IN (200,210) AND CTA_NVO_FACTOR_TASA IN (72.00,80.00,80.00,80.00,80.50,81.50) then 'T4'
    when C.TIP_INF IN (200,210) AND CTA_NVO_FACTOR_TASA IN (80.00,85.00,85.00,84.00,84.50,85.50) then 'T5'
    when C.TIP_INF IN (200,210) AND CTA_NVO_FACTOR_TASA IN (32.00,37.50,38.71,38.80,39.05,39.55, 29.43) then 'TASA EMPL'
    else 'Otros' 
END CTA_TASA_RBP_FLG,
CAST(NULL AS INTEGER) AS SYS_FTE,
CAST(NULL AS DATE) AS CTA_FCH_ULT_CMP,
CAST(NULL AS NUMERIC) AS CTA_NUM_EMPL_LIV,
CAST(NULL AS NUMERIC) AS CVE_ESTR,
CAST(NULL AS NUMERIC) AS CANT_TRN,
CAST(NULL AS NUMERIC) AS CTA_TRACK,
CAST(NULL AS STRING) AS CTA_SCORE,
CAST(NULL AS INTEGER) AS CTE_EDAD,
CAST(NULL AS INTEGER) AS CTE_GEN,
CAST(NULL AS STRING) AS SEXO,
CAST(NULL AS INTEGER) AS FCH_CARGA_EJEC,
CASE WHEN S.CTA_CVE=Z.CTA_CVE THEN 1 ELSE 0 END AS FLG_WEB,
'0' AS FLG_OFF,
CAST(NULL AS INTEGER) AS RANG_ANIO_ALTA,
CURRENT_DATE('America/Mexico_City') AS FCH_CARGA
FROM BASE_SOBREGIROS Z
LEFT JOIN SDO_CTA_Y C
  ON C.CTA_CVE = Z.CTA_CVE
LEFT JOIN `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_CTA` CTA_INFO
  ON CTA_INFO.CTA_CVE = Z.CTA_CVE
LEFT JOIN CTE_CLIE_FTES CF
  ON CF.CTA_CVE = C.CTA_CVE
LEFT JOIN SEGMENTO_CTE SSEG
  ON SSEG.CTA_CVE = C.CTA_CVE 
  AND SSEG.ANIO = C.ANIO AND SSEG.MES = C.MES
LEFT JOIN SEGMENTO_RFM RFM
  ON RFM.CTA_CVE = C.CTA_CVE 
  AND RFM.ANIO = C.ANIO AND RFM.MES =C.MES
LEFT JOIN INTERES_MSI_AGG IMP
  ON IMP.CTA_CVE = C.CTA_CVE 
  AND IMP.ANIO =C.ANIO AND IMP.MES = C.MES
LEFT JOIN CTE_MICREDITO R
  ON R.CTA_CVE = C.CTA_CVE
LEFT JOIN AGG_CAST Q
  ON Q.CTA_CVE = C.CTA_CVE 
  AND Q.ANIO = C.ANIO AND Q.MES = C.MES
LEFT JOIN AGG_QUITA P
  ON P.CTA_TRACK = C.CTA_CVE 
  AND P.ANIO = C.ANIO AND P.MES = C.MES
LEFT JOIN MACROSEG M
  ON M.CTA_CVE = C.CTA_CVE 
  AND EXTRACT(YEAR FROM M.FCH_MAX) = C.ANIO AND EXTRACT(MONTH FROM M.FCH_MAX) = C.MES
LEFT JOIN CVE_ZONA_SBB SBB
  ON SBB.TDA_CVE = C.CTA_TDA_APE
LEFT JOIN VDIM_TDA TD
  ON TD.TDA_CVE = C.CTA_TDA_APE
LEFT JOIN ING_INF ING 
  ON ING.CTA_TRACK = C.CTA_CVE
  AND ING.ANIO = C.ANIO AND ING.MES = C.MES
LEFT JOIN AGREGADO_TARJETAS TRJ
  ON TRJ.CTA_CVE = Z.CTA_CVE
LEFT JOIN POLIZAS_PIF POL
  ON POL.CTA_CVE = Z.CTA_CVE
LEFT JOIN WEB S
  ON Z.CTA_CVE = S.CTA_CVE
  AND Z.ANIO_ESTR = S.ANIO 
  AND Z.MES_ESTR = S.MES
WHERE
  C.CTA_EDO_CVE NOT IN ('T')
  AND ((C.ANIO - Z.ANIO_ESTR) * 12 + (C.MES - Z.MES_ESTR)) >= 0;
