CREATE OR REPLACE TABLE `crp-pro-cx-analitica.mus_pro_negfin_tablas_finales.FAC_NEGFIN_TM_JUSTME` AS

WITH BASE_LIV AS (
  SELECT
    CTA_CVE,
    ANIO_ALTA AS ANIO_ESTR,
    MES_ALTA AS MES_ESTR,
    TIP_INF,
    LOG_CVE,
    TDA_ADM_CTA AS TDA_APE,
    CTA_FCH_ALTA,
    SEXO,
    CTE_FCH_NAC,
    ANIOMES_ALTA AS ANIOMES_ESTR,
    DATE_DIFF(CURRENT_DATE('America/Mexico_City'), DATE(CTE_FCH_NAC), YEAR) AS EDAD
  FROM `crp-pro-cx-analitica.mus_pro_negfin_tablas_finales.DIM_NEGFIN_TM_CTAS_NVS_JUSTME`
),

SDO_CTA_Y AS (
  SELECT
    CTA_CVE, ANIO, MES, TIP_INF, CTA_EDO_CVE, CTA_SDO_ACT,
    CCR_CVE_BLQ_UNO, CCR_CVE_BLQ_DOS, CTA_FACTOR_TASA,
    CTA_NVO_FACTOR_TASA, CTA_NIV_MOR, CTA_TOTALERO_FLG,
    CTA_IMP_LIM_CRD, CTA_MISC_CR_SCORE, CTA_FCH_BLQ_UNO, CTA_FCH_BLQ_DOS,
    LOG_CVE,
    (ANIO * 100 + MES) AS ANIOMES_OBS,
    (CTA_IMP_LIM_CRD - CTA_SDO_ACT) AS OTB,
    CASE 
      WHEN CTA_IMP_LIM_CRD IS NULL OR CTA_IMP_LIM_CRD = 0 THEN -1
      ELSE SAFE_DIVIDE(CTA_SDO_ACT, CTA_IMP_LIM_CRD) 
    END AS PCT_UTIL_RAW,
    -- Pre-cálculo de rangos para evitar saturar el SELECT final
    CASE
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD < 4000 THEN '1.-4,000'
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD < 7500 THEN '2.-4,001-7,499'
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD < 10000 THEN '3.-7,500-9,999'
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD < 15000 THEN '4.-10,000-14,999'
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD < 20000 THEN '5.-15,000-19,999'
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD < 30000 THEN '6.-20,000-29,999'
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD < 50000 THEN '7.-30,000-49,999'
      WHEN TIP_INF IN (100) AND CTA_IMP_LIM_CRD >= 50000 THEN '8.-50,000+'
      ELSE 'OTRO'
    END AS RANG_LIM_CRD,
    CASE
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT < 4000 THEN '1.-4,000'
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT < 7500 THEN '2.-4,001-7,499'
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT < 10000 THEN '3.-7,500-9,999'
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT < 15000 THEN '4.-10,000-14,999'
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT < 20000 THEN '5.-15,000-19,999'
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT < 30000 THEN '6.-20,000-29,999'
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT < 50000 THEN '7.-30,000-49,999'
      WHEN TIP_INF IN (100) AND CTA_SDO_ACT >= 50000 THEN '8.-50,000+'
      ELSE 'OTRO'
    END AS RANG_SDO_ACT
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_SDO_CTA_MES`
  WHERE LOG_CVE = 120 
    AND ANIO >= 2025 
    AND (ANIO * 100 + MES) >= 202512
),

SEGMENTO_CTE AS (
  SELECT * EXCEPT(rn) FROM (
    SELECT
      CTA_CVE, ANIO, MES, SEGMENTO_CLIENTE, CTE_CVE_UNICO,
      ROW_NUMBER() OVER (PARTITION BY CTA_CVE, ANIO, MES ORDER BY SEGMENTO_CLIENTE DESC) AS rn
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_SEGMENTO_CTE`
    WHERE ANIO >= 2025 AND (ANIO * 100 + MES) >= 202512
  ) WHERE rn = 1
),

SEGMENTO_RFM AS (
  SELECT CTA_CVE, ANIO, MES, RFM_CREDITO AS SEGMENTO_RFM
  FROM `crp-pro-cx-semantica.mus_pro_shared_views.VDIM_SGMTOS_RFM_HIST_AANF`
  WHERE ANIO >= 2025 AND (ANIO * 100 + MES) >= 202512
),

INTERES_MSI_AGG AS (
  SELECT
    CTA_CVE, ANIO, MES,
    SUM(CASE WHEN INDICADOR = 'INTERESES_FIN' THEN IMP ELSE 0 END) AS IMP_INT_FIN,
    SUM(CASE WHEN INDICADOR = 'INTERESES_MOR' THEN IMP ELSE 0 END) AS IMP_INT_MOR,
    SUM(CASE WHEN INDICADOR LIKE 'MSI%' THEN IMP ELSE 0 END) AS IMP_INT_MSI
  FROM `crp-pro-cx-semantica.mus_pro_negfin_shared_views.VFAC_NEGFIN_INTER_MSI`
  WHERE ANIO >= 2025 AND (ANIO * 100 + MES) >= 202512
  GROUP BY 1, 2, 3
),

CTE_MICREDITO AS (
  SELECT DISTINCT SAFE_CAST(CARD_NUMBER AS NUMERIC) AS CTA_CVE
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_CTE_MICREDITO`
  WHERE (ANIO * 100 + MES) >= 202512
),

AGG_TRN_UNIFICADO AS (
  SELECT
    CTA_CVE,
    EXTRACT(YEAR FROM FCH_FCH) AS ANIO,
    EXTRACT(MONTH FROM FCH_FCH) AS MES,
    SUM(CASE WHEN TRN_CVE BETWEEN 502 AND 517 THEN TRN_IMP ELSE 0 END) AS IMP_CAST,
    COUNT(CASE WHEN TRN_CVE BETWEEN 502 AND 517 AND TRN_IMP > 0 THEN 1 END) AS CANT_CAST,
    MAX(CASE WHEN TRN_CVE BETWEEN 502 AND 517 THEN FCH_FCH END) AS CTA_FCH_CASTIGO,
    SUM(CASE WHEN TRN_CVE IN (307,407,763,764) THEN TRN_IMP ELSE 0 END) AS IMP_QUITA,
    COUNT(CASE WHEN TRN_CVE IN (307,407,763,764) AND TRN_IMP > 0 THEN 1 END) AS CANT_QUITA
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VFAC_TRN_CRD`
  WHERE FCH_FCH >= '2025-12-14'
  GROUP BY 1, 2, 3
),

MACROSEG AS (
  SELECT * EXCEPT(RN) FROM (
    SELECT
      CTA_CVE, SEGMENTO_OFICIAL,
      EXTRACT(YEAR FROM FEC_MACROSEG) AS ANIO_M,
      EXTRACT(MONTH FROM FEC_MACROSEG) AS MES_M,
      ROW_NUMBER() OVER (PARTITION BY CTA_CVE, EXTRACT(YEAR FROM FEC_MACROSEG), EXTRACT(MONTH FROM FEC_MACROSEG) ORDER BY FEC_MACROSEG DESC) AS RN
    FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_MACROSEGMENTO`
  ) WHERE RN = 1
),

VDIM_TDA AS (
  SELECT TDA_CVE, TDA_ZNA
  FROM `crp-pro-dwh-semanticagold.EIL_DP_VDWH.VDIM_TDA`
),

ING_INF AS (
  SELECT 
    CTA_TRACK, PTI_TOT,
    EXTRACT(YEAR FROM FECHA_SEGUIMIENTO) AS ANIO_I,
    EXTRACT(MONTH FROM FECHA_SEGUIMIENTO) AS MES_I
  FROM `crp-pro-dwh-semanticagold.MUS_PRO_DWH_VIEWS_ODS.VFAC_NEGFIN_ING_INFERIDO`
  WHERE FECHA_SEGUIMIENTO >= '2025-01-01'
),
SOLIC AS(
  SELECT 
    BR_ORG, LOG_CVE,CTA_CVE,BR_STATUS,
    BR_STT_CRED_DES 
    FROM crp-pro-dwh-semanticagold.EIL_DP_VMASTER.VFAC_NEGFIN_SOLICITUDES
    WHERE BR_ORG = 100 AND LOG_CVE = 120 AND DT_FCH_SOL >= '2025-12-14'
)

SELECT
  Z.CTA_CVE,
  Z.ANIO_ESTR,
  Z.MES_ESTR,
  Z.TIP_INF,
  Z.LOG_CVE,
  Z.CTA_FCH_ALTA,
  Z.SEXO,
  Z.CTE_FCH_NAC,
  Z.ANIOMES_ESTR,
  C.ANIO AS ANIO_OBS,
  C.MES AS MES_OBS,
  C.CTA_EDO_CVE,
  C.CTA_SDO_ACT,
  Z.TDA_APE,
  C.CCR_CVE_BLQ_UNO,
  C.CCR_CVE_BLQ_DOS,
  C.CTA_FACTOR_TASA,
  C.CTA_NVO_FACTOR_TASA,
  C.CTA_NIV_MOR,
  CASE WHEN C.CTA_NIV_MOR >= 2 THEN 1 ELSE 0 END AS ENTRY,
  C.CTA_TOTALERO_FLG,
  C.CTA_IMP_LIM_CRD,
  C.CTA_MISC_CR_SCORE,
  CASE 
    WHEN C.CTA_MISC_CR_SCORE = 0   THEN 'F. No calificado'
    WHEN C.CTA_MISC_CR_SCORE < 456 THEN 'E. Very high'
    WHEN C.CTA_MISC_CR_SCORE < 526 THEN 'D. High'
    WHEN C.CTA_MISC_CR_SCORE < 604 THEN 'C. Medium'
    WHEN C.CTA_MISC_CR_SCORE < 662 THEN 'B. Low'
    ELSE 'A. Very low'
  END AS NIV_RIESGO,
  C.OTB,
  C.PCT_UTIL_RAW AS PCT_UTIL,
  C.ANIOMES_OBS,
  CASE 
    WHEN C.CTA_NIV_MOR IN (0,1) THEN '0.-CTAS_VIG'
    WHEN C.CTA_NIV_MOR = 2 THEN '1.-1-29 DIAS'
    WHEN C.CTA_NIV_MOR = 3 THEN '2.-30_DIAS'
    WHEN C.CTA_NIV_MOR = 4 THEN '3.-60_DIAS'
    WHEN C.CTA_NIV_MOR = 5 THEN '4.-90_DIAS'
    WHEN C.CTA_NIV_MOR = 6 THEN '5.-120_DIAS'
    WHEN C.CTA_NIV_MOR = 7 THEN '6.-150_DIAS'
    WHEN C.CTA_NIV_MOR = 8 THEN '7.-180_DIAS'
    ELSE '8.-210_DIAS' 
  END AS RANG_NIV_MOR,
  CASE
    WHEN C.PCT_UTIL_RAW <= .20 THEN 'A.1-20'
    WHEN C.PCT_UTIL_RAW <= .25 THEN 'B.21-25'
    WHEN C.PCT_UTIL_RAW <= .30 THEN 'C.26-30'
    WHEN C.PCT_UTIL_RAW <= .35 THEN 'D.31-35'
    WHEN C.PCT_UTIL_RAW <= .40 THEN 'E.36-40'
    WHEN C.PCT_UTIL_RAW <= .45 THEN 'F.41-45'
    WHEN C.PCT_UTIL_RAW <= .50 THEN 'G.46-50'
    WHEN C.PCT_UTIL_RAW <= .75 THEN 'H.51-75'
    WHEN C.PCT_UTIL_RAW <= .85 THEN 'I.76-85'
    ELSE 'J.86+'
  END AS RANG_UTILIZA,
  C.RANG_SDO_ACT,
  C.RANG_LIM_CRD,
  CASE
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA NOT IN ('OTRO','VAD','1','2','3','4','5','6','7','8','9')) THEN 'Otro'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = 'VAD') THEN 'Canal Digital'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '1') THEN '1. Metro Sur'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '2') THEN '2. Metro Norte'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '3') THEN '3. Centro'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '4') THEN '4. Occidente'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '5') THEN '5. Golfo'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '6') THEN '6. Noreste'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '7') THEN '7. Bajio'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '8') THEN '8. Noroeste'
    WHEN (Z.TIP_INF IN (100,110) AND TD.TDA_ZNA = '9') THEN '9. Sureste'
    ELSE 'Otro'
  END AS CVE_ZNA,
  SSEG.CTE_CVE_UNICO,
  SSEG.SEGMENTO_CLIENTE,
  Z.EDAD,
  CASE WHEN Z.SEXO = 'M' THEN 'MASCULINO' WHEN Z.SEXO = 'F' THEN 'FEMENINO' ELSE 'SIN GENERO' END AS GENERO,
  ING.PTI_TOT AS PTI,
  RFM.SEGMENTO_RFM,
  ((C.ANIO - Z.ANIO_ESTR) * 12 + (C.MES - Z.MES_ESTR)) AS ANTIG_ESTR,
  CASE WHEN R.CTA_CVE IS NULL THEN 0 ELSE 1 END AS FLG_DIG,
  M.SEGMENTO_OFICIAL AS MACROSEGMENTO,
  COALESCE(IMP.IMP_INT_MOR, 0) AS IMP_INT_MOR,
  COALESCE(IMP.IMP_INT_FIN, 0) AS IMP_INT_FIN,
  COALESCE(IMP.IMP_INT_MOR,0) + COALESCE(IMP.IMP_INT_FIN,0) AS IMP_INT_TOT,
  COALESCE(IMP.IMP_INT_MSI, 0) AS IMP_INT_MSI,
  CASE WHEN C.CTA_NIV_MOR IN (3,4,5,6,7,8,9) THEN 1 ELSE 0 END AS FLG_30,
  CASE WHEN C.CTA_NIV_MOR IN (5,6,7,8,9) THEN 1 ELSE 0 END AS FLG_90,
  COALESCE(TRN.IMP_CAST, 0) AS IMP_CAST,
  COALESCE(TRN.CANT_CAST, 0) AS CANT_CAST, 
  COALESCE(TRN.IMP_QUITA, 0) AS IMP_QUITA,
  COALESCE(TRN.CANT_QUITA, 0) AS CANT_QUITA,
  TRN.CTA_FCH_CASTIGO AS CTA_FCH_CASTIGO,
  CASE 
    WHEN EDAD >= 18 AND EDAD <= 20 THEN "18-20"
    WHEN EDAD > 20 AND EDAD <= 24 THEN "21-24"
    WHEN EDAD >= 25 AND EDAD <= 29 THEN "25-29"
    WHEN EDAD > 29 AND EDAD <= 37 THEN "30-37"
    WHEN EDAD > 37 AND EDAD <= 44 THEN "38-44"
    WHEN EDAD > 44 AND EDAD <= 59 THEN "45-59"
    WHEN EDAD >= 60 THEN "60 +" 
  END AS RANG_EDAD,
  CASE
    WHEN C.TIP_INF IN (100,110) AND C.CTA_NVO_FACTOR_TASA IN (36.39,33.89,32.89,32.39,31.39,29.49,27.99,25.99) THEN 'T1'
    WHEN C.TIP_INF IN (100,110) AND C.CTA_NVO_FACTOR_TASA IN (49.54,47.04,46.04,45.54,42.04,39.49,37.99,33.99) THEN 'T2'
    WHEN C.TIP_INF IN (100,110) AND C.CTA_NVO_FACTOR_TASA IN (58.86,56.36,55.36,54.86,53.11,55,49.89,48.39,44.39) THEN 'T3'
    WHEN C.TIP_INF IN (100,110) AND C.CTA_NVO_FACTOR_TASA IN (66.20,63.70,62.70,62.20,61.2,57.49,55.99,51.99) THEN 'T4'
    WHEN C.TIP_INF IN (100,110) AND C.CTA_NVO_FACTOR_TASA IN (68,65.5,64.5,64,66,65.49,63.99,59.99) THEN 'T5'
    WHEN C.TIP_INF IN (100,110) AND C.CTA_NVO_FACTOR_TASA IN (29.43,28.18,27.68,27.43,26.55,24.95,24.20,22.20) THEN 'TASA EMPL'
    WHEN C.TIP_INF IN (100,110) AND C.CTA_NVO_FACTOR_TASA IN (14.99,15.49,16.49,18.99) THEN 'T0'
    WHEN C.TIP_INF IN (200,210) AND C.CTA_NVO_FACTOR_TASA IN (48.99,56.70,60.36,60.86,61.86) THEN 'T1'
    WHEN C.TIP_INF IN (200,210) AND C.CTA_NVO_FACTOR_TASA IN (55.99,65.60,69.83,70.33,71.33) THEN 'T2'
    WHEN C.TIP_INF IN (200,210) AND C.CTA_NVO_FACTOR_TASA IN (63.99,75.00,77.42,77.60,78.10,79.10) THEN 'T3'
    WHEN C.TIP_INF IN (200,210) AND C.CTA_NVO_FACTOR_TASA IN (72.00,80.00,80.50,81.50) THEN 'T4'
    WHEN C.TIP_INF IN (200,210) AND C.CTA_NVO_FACTOR_TASA IN (80.00,85.00,84.00,84.50,85.50) THEN 'T5'
    WHEN C.TIP_INF IN (200,210) AND C.CTA_NVO_FACTOR_TASA IN (32.00,37.50,38.71,38.80,39.05,39.55, 29.43) THEN 'TASA EMPL'
    ELSE 'Otros' 
  END AS TASA_RBP,
  S.BR_STATUS,
  S.BR_STT_CRED_DES,
  CURRENT_DATE('America/Mexico_City') AS FCH_CARGA
FROM BASE_LIV Z
LEFT JOIN SDO_CTA_Y C ON C.CTA_CVE = Z.CTA_CVE
LEFT JOIN SEGMENTO_CTE SSEG ON SSEG.CTA_CVE = Z.CTA_CVE AND SSEG.ANIO = C.ANIO AND SSEG.MES = C.MES
LEFT JOIN SEGMENTO_RFM RFM ON RFM.CTA_CVE = Z.CTA_CVE AND RFM.ANIO = C.ANIO AND RFM.MES = C.MES
LEFT JOIN INTERES_MSI_AGG IMP ON IMP.CTA_CVE = Z.CTA_CVE AND IMP.ANIO = C.ANIO AND IMP.MES = C.MES
LEFT JOIN CTE_MICREDITO R ON R.CTA_CVE = Z.CTA_CVE
LEFT JOIN AGG_TRN_UNIFICADO TRN ON TRN.CTA_CVE = Z.CTA_CVE AND TRN.ANIO = C.ANIO AND TRN.MES = C.MES
LEFT JOIN MACROSEG M ON M.CTA_CVE = Z.CTA_CVE AND M.ANIO_M = C.ANIO AND M.MES_M = C.MES
LEFT JOIN VDIM_TDA TD ON TD.TDA_CVE = Z.TDA_APE
LEFT JOIN ING_INF ING ON ING.CTA_TRACK = Z.CTA_CVE AND ING.ANIO_I = C.ANIO AND ING.MES_I = C.MES
LEFT JOIN SOLIC S ON S.CTA_CVE = Z.CTA_CVE 
WHERE  C.CTA_EDO_CVE NOT IN ('T')
  AND ((C.ANIO - Z.ANIO_ESTR) * 12 + (C.MES - Z.MES_ESTR)) >= 0;
